### ISSUE TITLE
Handling ghost blocks

### ISSUE THREAD

**Issue by MWHunter** [MWHunter/Grim#180]

**Comment by MWHunter** [comment]
Best solution is to resend players blocks 8x8x8 blocks around the player when they are getting violations that look like ghost blocks.

For blocks that are there on the server but not the client

One way to do it is the Verus/Kauri way, checking if the player's y is on a multiple of 0.015625.

Problems with this way:
- We are open source, cheat makers will just make everything look like a ghost block


Another way is to make a list of all the changed blocks in the player's chunk cache.

To do this, we need 65536 bits per chunk, or 8.192 KiB.

If a player is getting excessive violations that look like a ghost block, such as trying to move into a block, resend chunks.  If a player continues, punish them.  We have a chunk cache so doing this won't slow down the server.

Problems with this way:
- It tells the user to stop cheating, so we might lose cheaters by doing this
- The chunk cache MIGHT be a tick off for block breaking/placing, although it shouldn't be.

**Comment by Jaren8r** [comment]
> It tells the user to stop cheating, **so we might lose cheaters by doing this**

Isn't that the entire point of an anti cheat?

**Comment by MWHunter** [comment]
I probably meant that it could help cheaters know they were flagging the anticheat, although there's not much point to preventing that.

**Comment by MWHunter** [comment]
Fixed by some spaghetti code that somehow works
