### ISSUE TITLE
Version placeholder not working at startup

### ISSUE THREAD

**Issue by tommasobenatti** [MWHunter/Grim#245]
I just wanted to report this little bug when starting the plugin
![image](https://user-images.githubusercontent.com/62927722/121757691-ac978280-cb1e-11eb-97c5-57a316c8dc7f.png)

Also when disabling
![image](https://user-images.githubusercontent.com/62927722/121757743-d5b81300-cb1e-11eb-8922-2e91865be1f3.png)

**Comment by MWHunter** [comment]
Fixed by enabling resource filtering
