### ISSUE TITLE
Walking on slabs falses on 1.8 server

### ISSUE THREAD

**Issue by Bentley1201** [MWHunter/Grim#250]
Just thought I'd mention since I don't see an open issue, regardless... amazing work so far! ![Screen Shot 2021-06-18 at 6 46 15 PM](https://user-images.githubusercontent.com/85256776/122624381-86656b80-d065-11eb-84dc-94246e8dc91c.png)

**Comment by MWHunter** [comment]
Oh wow, 1.8 support still works.  Anyways, fixed by also searching for STEP in material names as I was only searching for SLAB while in 1.8 they are called steps.
