### ISSUE TITLE
LibsDisguise, view selfDisguise is not visible client side.

### ISSUE THREAD

**Issue by Fox2Code** [MWHunter/Grim#256]
How to reproduce: `/disguise Fox setSelfDisguiseVisible true`

SelfDisguise use an entityID that doesn't exists on the server, this seem to cause issues with GrimAC

With GrimAC the self disguise is invisible.
Without GrimAC everything work fine.

**Comment by MWHunter** [comment]
Assuming fixed with packetevents 2.0 as all entities are packet based in 2.0
