### ISSUE TITLE
Corner stairs false 

### ISSUE THREAD

**Issue by Bentley1201** [MWHunter/Grim#270]
![Screen Shot 2021-07-13 at 2 47 57 PM](https://user-images.githubusercontent.com/85256776/125515696-f5cd647e-5c54-41bf-9bdd-30bc0989da35.png)
1.17 on a 1.8 server

**Comment by MWHunter** [comment]
Is ViaVersion up to date?  That stair should be connecting as a corner stair as it is physically impossible for it to not connect on 1.8, but ViaVersion is sending the wrong stair block data.

**Comment by Bentley1201** [comment]
ViaVersion-4.0.2-SNAPSHOT.jar

**Comment by MWHunter** [comment]
Can you share the link that "/viaversion dump" gives?

**Comment by Bentley1201** [comment]
Ah sorry, enabling `serverside-blockconnections` fixed it. However, it might be good to mention that somewhere (whenever it releases)  so someone else doesn't run into the same issue.
