### ISSUE TITLE
FastBridge / Onestack

### ISSUE THREAD

**Issue by SquareCodeFX** [MWHunter/Grim#272]
Take a look at the construction techniques. These make the anticheat throw red messages.

**Comment by MWHunter** [comment]
Client and server version?

**Comment by SquareCodeFX** [comment]
1.8.8 default + paper spigot 1.8.8

**Comment by SquareCodeFX** [comment]
In general, there still seem to be difficulties with regard to the placement of blocks

**Comment by MWHunter** [comment]
I believe I figured it out, 1.8 sends the place block packet but the position was the block that it was placed on, instead of the position of the block placed.  Block placing should work fine on 1.9 and above and in modern versions I'm getting the tick it was placed fine.

**Comment by SquareCodeFX** [comment]
I hope you can fix the problem and calculate it even better

**Comment by MWHunter** [comment]
Pushed an attempted fix, let me know if it fixes as I can't test stuff well right now

**Comment by MWHunter** [comment]
Fixed as of 306d9bc
- I was checking if the server version was older than 1.8 instead of 1.8.8, so the code wasn't running
- I wasn't breaking on the switch statement from the previous commit so it was adding random things to the position
