### ISSUE TITLE
Walking while blocking on 1.8 server on 1.9+ clients falses

### ISSUE THREAD

**Issue by Bentley1201** [MWHunter/Grim#277]
1.8 servers don't have shields but blocking on a 1.9+ client will still spawn a shield while blocking that slows down the player's velocity.

**Comment by MWHunter** [comment]
Thanks ViaVersion!

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/57f9119eedaf7b6b3a18cf6f6100c8c3adaee861
