### ISSUE TITLE
Desync when switching hotbar slots with a shield quickly

### ISSUE THREAD

**Issue by Bentley1201** [MWHunter/Grim#278]
Hold down right click to start blocking with shield, start sprinting, go back and forth between the shield and another slot really quickly without lifting right click and it will false

**Comment by MWHunter** [comment]
I blame https://github.com/MWHunter/Grim/commit/40d565b627d86047b5260f84f00b7e37bcaadd8a

**Comment by MWHunter** [comment]
Fixed, too many stupid mojang decisions to explain.

**Comment by Bentley1201** [comment]
I am still able to replicate it 
![desync](https://user-images.githubusercontent.com/85256776/128426328-64d1185e-9483-458a-92b2-0374edec1ca7.png)
