### ISSUE TITLE
Fast Elytra Fly into Water falses sometimes

### ISSUE THREAD

**Issue by pianoman911** [MWHunter/Grim#285]
If you fly high and then fly into the water pretty fast, there are some falses.
Tested in 1.15.2
![image](https://user-images.githubusercontent.com/47421010/129480354-b9940ef7-cb93-493e-be43-492855563489.png)

**Comment by MWHunter** [comment]
Most likely fixed by the PlayerBaseTick changes in https://github.com/MWHunter/Grim/commit/a71e791a10a6360111563436f2f54b9397ecad38
