### ISSUE TITLE
Error on join with setback

### ISSUE THREAD

**Issue by Twiz0x** [MWHunter/Grim#292]
java.lang.Exception
[13:03:19 WARN]: at ac.grim.grimac.manager.SetbackTeleportUtil.executeSetback(SetbackTeleportUtil.java:83)
[13:03:19 WARN]: at ac.grim.grimac.predictionengine.MovementCheckRunner.processAndCheckMovementPacket(MovementCheckRunner.java:82)
>[13:03:19 WARN]: at ac.grim.grimac.checks.impl.movement.PredictionRunner.onPositionUpdate(PredictionRunner.java:16)
[13:03:19 WARN]: at ac.grim.grimac.manager.CheckManager.lambda$onPositionUpdate$2(CheckManager.java:88)
[13:03:19 WARN]: at java.lang.Iterable.forEach(Iterable.java:75)
[13:03:19 WARN]: at ac.grim.grimac.manager.CheckManager.onPositionUpdate(CheckManager.java:88)
>[13:03:19 WARN]: at ac.grim.grimac.events.packets.CheckManagerListener.onPacketPlayReceive(CheckManagerListener.java:91)
[13:03:19 WARN]: at io.github.retrooper.packetevents.event.impl.PacketPlayReceiveEvent.call(PacketPlayReceiveEvent.java:61)
[13:03:19 WARN]: at io.github.retrooper.packetevents.event.manager.EventManagerModern.callEvent(EventManagerModern.java:54)
[13:03:19 WARN]: at io.github.retrooper.packetevents.event.manager.EventManager.callEvent(EventManager.java:52)
>[13:03:19 WARN]: at io.github.retrooper.packetevents.processor.PacketProcessorInternal.read(PacketProcessorInternal.java:108)
[13:03:19 WARN]: at io.github.retrooper.packetevents.injector.modern.PlayerChannelHandlerModern.channelRead(PlayerChannelHandlerModern.java:37)
[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:03:19 WARN]: at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
[13:03:19 WARN]: at dev._2lstudios.hamsterapi.handlers.HamsterChannelHandler.channelRead(HamsterChannelHandler.java:57)
[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:03:19 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:168)
[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
>[13:03:19 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
>[13:03:19 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
>>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:03:19 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
>[13:03:19 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:03:19 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
>[13:03:19 WARN]: at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
>>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
>[13:03:19 WARN]: at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
[13:03:19 WARN]: at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
[13:03:19 WARN]: at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
[13:03:19 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
>[13:03:19 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
>[13:03:19 WARN]: at java.lang.Thread.run(Thread.java:748)
[13:03:19 INFO]: [GrimAC] Setback Twiz0x_x
[13:03:19 WARN]: java.lang.Exception
>>[13:03:19 WARN]: at ac.grim.grimac.manager.SetbackTeleportUtil.executeSetback(SetbackTeleportUtil.java:83)
>[13:03:19 WARN]: at ac.grim.grimac.predictionengine.MovementCheckRunner.processAndCheckMovementPacket(MovementCheckRunner.java:82)
[13:03:19 WARN]: at ac.grim.grimac.checks.impl.movement.PredictionRunner.onPositionUpdate(PredictionRunner.java:16)
>[13:03:19 WARN]: at ac.grim.grimac.manager.CheckManager.lambda$onPositionUpdate$2(CheckManager.java:88)
[13:03:19 WARN]: at java.lang.Iterable.forEach(Iterable.java:75)
[13:03:19 WARN]: at ac.grim.grimac.manager.CheckManager.onPositionUpdate(CheckManager.java:88)
>[13:03:19 WARN]: at ac.grim.grimac.events.packets.CheckManagerListener.onPacketPlayReceive(CheckManagerListener.java:91)
>[13:03:19 WARN]: at io.github.retrooper.packetevents.event.impl.PacketPlayReceiveEvent.call(PacketPlayReceiveEvent.java:61)
>[13:03:19 WARN]: at io.github.retrooper.packetevents.event.manager.EventManagerModern.callEvent(EventManagerModern.java:54)
>[13:03:19 WARN]: at io.github.retrooper.packetevents.event.manager.EventManager.callEvent(EventManager.java:52)
[13:03:19 WARN]: at io.github.retrooper.packetevents.processor.PacketProcessorInternal.read(PacketProcessorInternal.java:108)
>>[13:03:19 WARN]: at io.github.retrooper.packetevents.injector.modern.PlayerChannelHandlerModern.channelRead(PlayerChannelHandlerModern.java:37)
[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
>[13:03:19 WARN]: at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
[13:03:19 WARN]: at dev._2lstudios.hamsterapi.handlers.HamsterChannelHandler.channelRead(HamsterChannelHandler.java:57)
[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
>[13:03:19 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:168)
[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
>[13:03:19 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
>[13:03:19 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
>>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[13:03:19 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:03:19 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
>[13:03:19 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
>[13:03:19 WARN]: at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
>[13:03:19 WARN]: at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
>[13:03:19 WARN]: at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
>[13:03:19 WARN]: at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
>[13:03:19 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
>[13:03:19 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
>[13:03:19 WARN]: at java.lang.Thread.run(Thread.java:748)
>[13:03:19 INFO]: [GrimAC] Setback Twiz0x_x
>[13:03:19 WARN]: java.lang.Exception
>[13:03:19 WARN]: at ac.grim.grimac.manager.SetbackTeleportUtil.executeSetback(SetbackTeleportUtil.java:83)
>[13:03:19 WARN]: at ac.grim.grimac.predictionengine.MovementCheckRunner.processAndCheckMovementPacket(MovementCheckRunner.java:82)
>[13:03:19 WARN]: at ac.grim.grimac.checks.impl.movement.PredictionRunner.onPositionUpdate(PredictionRunner.java:16)
>[13:03:19 WARN]: at ac.grim.grimac.manager.CheckManager.lambda$onPositionUpdate$2(CheckManager.java:88)
>[13:03:19 WARN]: at java.lang.Iterable.forEach(Iterable.java:75)
>[13:03:19 WARN]: at ac.grim.grimac.manager.CheckManager.onPositionUpdate(CheckManager.java:88)
>[13:03:19 WARN]: at ac.grim.grimac.events.packets.CheckManagerListener.onPacketPlayReceive(CheckManagerListener.java:91)
>[13:03:19 WARN]: at io.github.retrooper.packetevents.event.impl.PacketPlayReceiveEvent.call(PacketPlayReceiveEvent.java:61)
>[13:03:19 WARN]: at io.github.retrooper.packetevents.event.manager.EventManagerModern.callEvent(EventManagerModern.java:54)
>[13:03:19 WARN]: at io.github.retrooper.packetevents.event.manager.EventManager.callEvent(EventManager.java:52)
>[13:03:19 WARN]: at io.github.retrooper.packetevents.processor.PacketProcessorInternal.read(PacketProcessorInternal.java:108)
>[13:03:19 WARN]: at io.github.retrooper.packetevents.injector.modern.PlayerChannelHandlerModern.channelRead(PlayerChannelHandlerModern.java:37)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
>[13:03:19 WARN]: at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
>[13:03:19 WARN]: at dev._2lstudios.hamsterapi.handlers.HamsterChannelHandler.channelRead(HamsterChannelHandler.java:57)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
>[13:03:19 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:168)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
>[13:03:19 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
>[13:03:19 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
>[13:03:19 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
>[13:03:19 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
>[13:03:19 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
>[13:03:19 WARN]: at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
>[13:03:19 WARN]: at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
>[13:03:19 WARN]: at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
>[13:03:19 WARN]: at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
>[13:03:19 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
>[13:03:19 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
>[13:03:19 WARN]: at java.lang.Thread.run(Thread.java:748)
>[13:03:19 INFO]: [GrimAC] Setback Twiz0x_x
>[13:03:19 WARN]: java.lang.Exception
>[13:03:19 WARN]: at ac.grim.grimac.manager.SetbackTeleportUtil.executeSetback(SetbackTeleportUtil.java:83)
>[13:03:19 WARN]: at ac.grim.grimac.predictionengine.MovementCheckRunner.processAndCheckMovementPacket(MovementCheckRunner.java:82)
>[13:03:19 WARN]: at ac.grim.grimac.checks.impl.movement.PredictionRunner.onPositionUpdate(PredictionRunner.java:16)
>[13:03:19 WARN]: at ac.grim.grimac.manager.CheckManager.lambda$onPositionUpdate$2(CheckManager.java:88)
>[13:03:19 WARN]: at java.lang.Iterable.forEach(Iterable.java:75)
>[13:03:19 WARN]: at ac.grim.grimac.manager.CheckManager.onPositionUpdate(CheckManager.java:88)
>[13:03:19 WARN]: at ac.grim.grimac.events.packets.CheckManagerListener.onPacketPlayReceive(CheckManagerListener.java:91)
>[13:03:19 WARN]: at io.github.retrooper.packetevents.event.impl.PacketPlayReceiveEvent.call(PacketPlayReceiveEvent.java:61)
>[13:03:19 WARN]: at io.github.retrooper.packetevents.event.manager.EventManagerModern.callEvent(EventManagerModern.java:54)
>[13:03:19 WARN]: at io.github.retrooper.packetevents.event.manager.EventManager.callEvent(EventManager.java:52)
>[13:03:19 WARN]: at io.github.retrooper.packetevents.processor.PacketProcessorInternal.read(PacketProcessorInternal.java:108)
>[13:03:19 WARN]: at io.github.retrooper.packetevents.injector.modern.PlayerChannelHandlerModern.channelRead(PlayerChannelHandlerModern.java:37)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
>[13:03:19 WARN]: at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
>[13:03:19 WARN]: at dev._2lstudios.hamsterapi.handlers.HamsterChannelHandler.channelRead(HamsterChannelHandler.java:57)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
>[13:03:19 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:168)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
>[13:03:19 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
>[13:03:19 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
>[13:03:19 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
>>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:03:19 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:03:19 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
>[13:03:19 WARN]: at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
>[13:03:19 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
>[13:03:19 WARN]: at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
[13:03:19 WARN]: at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
[13:03:19 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
[13:03:19 WARN]: at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
[13:03:19 WARN]: at java.lang.Thread.run(Thread.java:748)
[13:03:19 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
>>[13:03:19 INFO]: [GrimAC] Setback Twiz0x_x

**Comment by MWHunter** [comment]
this is just debug and not an error
