### ISSUE TITLE
Noslow Bypass

### ISSUE THREAD

**Issue by TypicalModMaker** [MWHunter/Grim#296]
NCP NoSlow bypasses (Rise 5.3)

[Youtube Video](https://youtu.be/aBGpVoJdRbw)

Plugins:
![image](https://user-images.githubusercontent.com/52781429/135667567-69753c58-f755-4c46-8bfc-0bbe7734ef7f.png)

**Comment by MWHunter** [comment]
that's what I get for copying ncp use item code...

**Comment by MWHunter** [comment]
I'll fix it with a post position check.  It works by releasing the item, sending position, and then using the item again right after it sends position.

**Comment by MWHunter** [comment]
fixed by 2.1.0
