### ISSUE TITLE
Scaffold Bypass

### ISSUE THREAD

**Issue by TypicalModMaker** [MWHunter/Grim#297]
Scaffold bypasses (Rise 5.3)
Sometimes it lagbacks (but doesn't flag) while bridging up
None rotation scaffold bypasses, other rotations flag for prediction medium
![image](https://user-images.githubusercontent.com/52781429/135669196-68107509-95d8-42ae-9d74-b954b5a89fc9.png)

Video:
[Youtube](https://youtu.be/3QXCsSuS9UA)

Plugins:
![image](https://user-images.githubusercontent.com/52781429/135669114-8e1fcef6-6384-4624-a35a-17a874ae7e6a.png)

**Comment by MWHunter** [comment]
There isn't even a scaffold check.

**Comment by TypicalModMaker** [comment]
i know but all other scaffolds flag for prediction, so might add not looking at block check or something

**Comment by jamesgames69** [comment]
Yikes imagine having an offsetting scaffold 😭

**Comment by TypicalModMaker** [comment]
> Yikes imagine having an offsetting scaffold 😭

Yikes imagine crying about it

**Comment by MWHunter** [comment]
This specific scaffolding should be flagged by the PositionPlace check.  More advanced ones might not but LiquidBounce is flagging and I don't know what other free and open source clients to test.
