### ISSUE TITLE
Semi disabler

### ISSUE THREAD

**Issue by TypicalModMaker** [MWHunter/Grim#298]
Only timer check isn't disabled

Basically u gotta fall/kill yourself but execute /heal command 1-5 milliseconds before dying 

(skip to 0:55)
Video:
[Youtube](https://www.youtube.com/watch?v=_darqLyg-wI&ab_channel=PackageHvH)

**Comment by MWHunter** [comment]
What plugin is the /heal command with?  EssentialsX doesn't allow dead players to be healed.

**Comment by MWHunter** [comment]
Anyways, should be fixed by https://github.com/MWHunter/Grim/commit/efa776c4ab1b4b62ee22a91a1e2b98a44cd91960
