### ISSUE TITLE
Make queue's runnables instead of the current solution

### ISSUE THREAD

**Issue by MWHunter** [MWHunter/Grim#313]
Object orientated programming.

No performance hit.

class PlayerUpdateBlockData implements Runnable {
int x,y,z,combined;
public PlayerUpdateBlockData(GrimPlayer player, int x, int y, int z, int combinedID) {
...
}

@override
public void run() {
player.compensatedWorld.setBlock(x, y, z, combinedID)
}

**Comment by DeprecatedProtocol** [comment]
You can use a ThreadFactory
https://docs.oracle.com/javase/9/docs/api/java/util/concurrent/ThreadFactory.html

**Comment by MWHunter** [comment]
fixed by using central transaction queue on local branch
