### ISSUE TITLE
Cannot hook into the end of tick

### ISSUE THREAD

**Issue by TypicalModMaker** [MWHunter/Grim#319]
**Describe the bug**
Basically, every time I start the server and everything loads it does not want to hook into the end of tick, and it spams the console.

**To Reproduce**
Video is preferred.   If video is not possible, for bypasses, the hacked client name, version, module, module settings, and the check being bypassed is enough.  For false positives, steps to reproduce is fine also.
Just use FoxSpigot and start the server
**Server Version:**
FoxSpigot 1.9
**Grim Version (Git commit or the version in the jar's name)**
0.0.3-all
**Relevant plugins**
Or all plugins if you are unsure
only grim.

**Comment by MWHunter** [comment]
Does this still happen with 2.0.2?  At this point, the injection method and place injected has changed so it's likely fixed.

**Comment by MWHunter** [comment]
I'm just assuming it's fixed on this shitty mcm fork as the new method shares few similarities with the old one
