### ISSUE TITLE
FP/Incompatibility with Citizens Sentinel combat NPCS.

### ISSUE THREAD

**Issue by timof121** [MWHunter/Grim#323]
**Describe the bug**
When a Citizens > Sentinel NPC hits you, sometimes you get flagged for Prediction-Medium or Ground Spoof.
**To Reproduce**
1. Download Grim, Citizens, and Sentinel.
2. Make an NPC that can hit you.
3. Make him hit u into a corner, and then wait.
4. You'll get flagged for Prediction-Medium or Ground Spoof
https://streamable.com/di7thh
**Server Version:**
NachoSpigot 1.8.8 (Paper Fork)
**Grim Version (Git commit or the version in the jar's name)**
8e35b739074875e25c3a5353761722687342c071 commit, grim 0.0.3
**Relevant plugins**
Citizens, Sentinel (Citizens addon for making combat npcs)

**Comment by MWHunter** [comment]
Fixed by PacketEvents 2.0

**Comment by MWHunter** [comment]
fixed by 0.03 rewrite

**Comment by timof121** [comment]
> fixed by 0.03 rewrite

Insane gaming 🎉
