### ISSUE TITLE
False positive on fence blockconnections with TNT

### ISSUE THREAD

**Issue by Pablete1234** [MWHunter/Grim#324]
**Describe the bug**
When you have fences next to tnt, the fences do not connect to the tnt but the AC acts as if they did, so walking on the edge of the tnt causes ground spoof and other checks to trigger

**To Reproduce**

https://user-images.githubusercontent.com/11789291/148479140-15e5a67e-e62d-4636-ba85-d6ce87a3dbb0.mp4

**Server Version:**
1.8.8

The client is in 1.18.1, server has viaversion installed

**Grim Version (Git commit or the version in the jar's name)**
GrimAC v0.0.3

**Relevant plugins**
none

**Comment by Weigurde** [comment]
bumping because this might be closed since it's made on a now outdated version of grim
also in the discord "Stop testing this jar, you aren't getting support and this jar has major errors!"

**Comment by MWHunter** [comment]
Change introduced on 1.12, will add that version difference.

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/065f3f78396be0f451a1110eb2e21bfb3727b2fd
