### ISSUE TITLE
You can't join the game when Matrix and Grim are running at the same time

### ISSUE THREAD

**Issue by NuymakStone** [MWHunter/Grim#325]
**Describe the bug**
You can't join the game when Matrix and Grim are running at the same time.But when you disable matrix or grim,then players can join in.

**To Reproduce**

https://user-images.githubusercontent.com/79128084/149642141-70440508-7f13-4565-92c5-b5c7a6c9ffdb.mp4

**Server Version:1.8.8**

**Grim Version Grim-0.0.3**

**Relevant plugins**
Matrix PraticePro Grim-0.0.3

**Comment by sadcenter** [comment]
I don't know is it really an issue since anti-cheats are rarely written to be compatible with other anti-cheats

**Comment by NuymakStone** [comment]
1
