### ISSUE TITLE
Slime is completely broken

### ISSUE THREAD

**Issue by Weigurde** [MWHunter/Grim#327]
**Describe the bug**
Jumping onto slime will spam 0.03 prediction errors and teleports until you slowly move off it.
Judging by where you get teleported, prediction is just in the air hovering.
**To Reproduce**
1. place slime block
2. jump on top
3. die
3.5. if you toggle some sort of fly (wurst fly works, for example) you stop flagging because you hover over the slime, but if you move at all you spam flags as expected

**Server Version:**
1.18.1
**Grim Version (Git commit or the version in the jar's name)**
2.0.0
**Relevant plugins**
tested on noah's test server
Or all plugins if you are unsure

**Comment by sadcenter** [comment]
Are you using fast math? Also are you sure this is NachoSpigot related (Is it working properly on other spigots e.g PaperSpigot)? Grim 2.0.0 has been released yesterday with re-write so it might contains bugs

**Comment by MWHunter** [comment]
Fixed in 2.0.1
