### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by lokka30** [MWHunter/Grim#329]
An issue template for questions and suggestions would be brilliant :) want me to PR this?

(Not a bug - please remove the label)

**Comment by sadcenter** [comment]
definitely a good point, people will know what information is important when creating issues

**Comment by MWHunter** [comment]
I'd accept the PR, but most people report stuff on discord

**Comment by lokka30** [comment]
Unless you've got a great tickets system going on, I believe you'd prefer people use the GH issue forms once this PR is merged, especially for software like this.

**Comment by lokka30** [comment]
PR was closed
