### ISSUE TITLE
Snow block false positive

### ISSUE THREAD

**Issue by LewUwU** [MWHunter/Grim#340]
**Describe the bug**
I joined the Test server and i runned & jumped in the snow block stair, the anticheat flagged Prediction

**To Reproduce**
1.8 Client (Not tested with others versions)
Run & Jump in the snow block stair

**Server Version:**
1.18.1

**Grim Version (Git commit or the version in the jar's name)**
Test server (The motd says 2.0.13, im not sure if is updated)

**Relevant plugins**
Test server plugins?

**Comment by MWHunter** [comment]
Unable to reproduce
