### ISSUE TITLE
Respawn anchor item missing client-side

### ISSUE THREAD

**Issue by Jyguy** [MWHunter/Grim#351]
**Describe the bug**
On 1.16.5, respawn anchors (as an item) do not show up on the client at all. It still exists on the server, so actions like placing or dropping works, it just doesn't show on the client. This does not happen on 1.17+. When Grim is removed, the bug doesn't happen and the item is visible again.

**To Reproduce**
https://youtu.be/MpCLeSEPk1Y

**Server Version:**
This server is running Paper version git-Paper-"fa1a7c180" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Grim Version (Git commit or the version in the jar's name)**
5802b7bc725eb2ad54dd297c56ca75f35bce2c90

**Relevant plugins**
Plugins (2): GrimAC, ProtocolLib

**Comment by MWHunter** [comment]
@retrooper

**Comment by MWHunter** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/85cb8a72ca37691dd5dca0d1405091deea8a5273
