### ISSUE TITLE
AntiKB false on respawn with 

### ISSUE THREAD

**Issue by ilovefuud** [MWHunter/Grim#357]
**Describe the bug**
On death with the game rule doImmediateRespawn enabled, you will flag antiKB

**To Reproduce**
[Video is preferred.   If video is not possible, for bypasses, the hacked client name, version, module, module settings, and the check being bypassed is enough.  For false positives, steps to reproduce is fine also.](https://youtu.be/7FW58l4hfVE)

**Server Version:**
1.16.5
**Grim Version (Git commit or the version in the jar's name)**
[2.1.12](https://github.com/MWHunter/Grim/commit/c5c7dfb0d08735fc0cb364958aa96d038f44fa83)**Relevant plugins**

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/140925e1c8caee74c73b81e98d4febe762ccfe98
