### ISSUE TITLE
Teleporting to someone far away in spectator mode sometimes gets you stuck in place

### ISSUE THREAD

**Issue by Jaren8r** [MWHunter/Grim#358]
**Describe the bug**
Teleporting to someone far away in spectator mode sometimes gets you stuck in place

**To Reproduce**
Run /gmsp and try teleporting to someone far away from you
[Video](https://youtu.be/OjqbSAP7VXo)

**Server Version:**
git-Valury-2 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)

**Grim Version (Git commit or the version in the jar's name)**
c5c7dfb

**Relevant plugins**
N/A

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/2313e00294a422edc3ba0553533a4d142a1b24b7
