### ISSUE TITLE
Pick block mostly not working

### ISSUE THREAD

**Issue by lerokko** [MWHunter/Grim#360]
**Describe the bug**
Pick block only works sometimes in creative but a lot of the pick block behavior and functions are missing.

**To Reproduce**
Join in survival. Have block in inventory. Click on that block somewhere placed in the world. It should be swapped with your hotbar item but nothing happens.

**Server Version:**
The server is running Paper version git-Paper-261 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 855637f)

**Grim Version (Git commit or the version in the jar's name)**
Grim Anticheat 2.1.2

**Relevant plugins**
Tested with only Grim Anticheat

**Comment by MWHunter** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/1452b65879d0d84c3421d1e1de0d0be89525295b
