### ISSUE TITLE
Grim 1.7player silmulation false

### ISSUE THREAD

**Issue by Abel156** [MWHunter/Grim#361]
**Describe the bug**

Issue: silmulation false appears when 1.7 player walks

**To Reproduce**
Video is preferred.   If video is not possible, for bypasses, the hacked client name, version, module, module settings, and the check being bypassed is enough.  For false positives, steps to reproduce is fine also.

Reproduce: use 1.7 client, enter the server, walk

**Server Version:**

 This server is running CraftBukkit version git-PaperSpigot-f6fba00-9935adc (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Grim Version (Git commit or the version in the jar's name)**

13673603d57fc47f605691ea70a65830113af07a

**Relevant plugins**
Or all plugins if you are unsure

Plugins (7): PlugMan, ViaVersion, PlaceholderAPI, ProtocolLib, MiniMOTD, ViaRewind, GrimAC

**Comment by MWHunter** [comment]
Works fine - even when testing 1.7 stepping,  Otherwise 1.7 and 1.8 should be identical.  Very likely was the fastmath issue.
