### ISSUE TITLE
Reach check is only flagged for the first few hits

### ISSUE THREAD

**Issue by Abel156** [MWHunter/Grim#366]
**Describe the bug**

Reach check is only flagged for the first few hits

**To Reproduce**
Video is preferred.   If video is not possible, for bypasses, the hacked client name, version, module, module settings, and the check being bypassed is enough.  For false positives, steps to reproduce is fine also.

https://youtu.be/d3DBqPg8ZvM

**Server Version:**

Foxspigot

**Grim Version (Git commit or the version in the jar's name)**

ddd344ffa5cb7f42a8dcd7bba2136d134a1373aa

**Relevant plugins**
Or all plugins if you are unsure

Plugins (7): PlugMan, ViaVersion, PlaceholderAPI, ProtocolLib, MiniMOTD, ViaRewind, GrimAC

**Comment by MWHunter** [comment]
Change the config to enable pre and post tick transactions.  That will make the reach check much more accurate as by default it's more meant for non-pvp servers where reach isn't really important.
