### ISSUE TITLE
1.7 Player using fastmath results in false

### ISSUE THREAD

**Issue by Abel156** [MWHunter/Grim#367]
**Describe the bug**

1.7 Player using fastmath results in false

**To Reproduce**
Video is preferred.   If video is not possible, for bypasses, the hacked client name, version, module, module settings, and the check being bypassed is enough.  For false positives, steps to reproduce is fine also.

https://youtu.be/LiTGPMdY0H0

**Server Version:**

Foxspigot

**Grim Version (Git commit or the version in the jar's name)**

ddd344ffa5cb7f42a8dcd7bba2136d134a1373aa

**Relevant plugins**
Or all plugins if you are unsure

Plugins (7): PlugMan, ViaVersion, PlaceholderAPI, ProtocolLib, MiniMOTD, ViaRewind, GrimAC

**Comment by Weigurde** [comment]
are you using the latest development versions of viaversion and protocollib? also, spigot forks cause problems with this, so try using normal spigot

**Comment by Abel156** [comment]
> 您使用的是最新的 viaversion 和 protocollib 开发版本吗？此外，插口叉会导致此问题，因此请尝试使用普通插口

ViaVersion-4.2.2-SNAPSHOT
ProtocolLib 5.0.0-SNAPSHOT-b551
Same problem when i use other spigot

**Comment by Abel156** [comment]
> are you using the latest development versions of viaversion and protocollib? also, spigot forks cause problems with this, so try using normal spigot

ViaVersion-4.2.2-SNAPSHOT
ProtocolLib 5.0.0-SNAPSHOT-b551
Same problem when i use other spigot

**Comment by MWHunter** [comment]
1.7 fastmath is now supported
