### ISSUE TITLE
IllegalStateException Error

### ISSUE THREAD

**Issue by Pledix** [MWHunter/Grim#368]
**Describe the bug**
I get this error on console:
https://pastebin.com/cK7gEuEn

**Server Version:** 
Purpur 1.18.2

**Grim Version (Git commit or the version in the jar's name)**
grimac-2.2.1-all

**Comment by MWHunter** [comment]
Fixed by removing teleport event in https://github.com/MWHunter/Grim/commit/80ecc6b172de7d4d9e8566c6bec497a9984f6d2a
