### ISSUE TITLE
PacketEvents Event is null

### ISSUE THREAD

**Issue by Pantera07** [MWHunter/Grim#369]
**Describe the bug**
i got error message
https://pastebin.com/UYTXzNQW

**Server Version:**
Purpur 1.18.2 #1609

**Grim Version (Git commit or the version in the jar's name)**
grimac-2.2.1-all

**Relevant plugins**
ProtocolLib 5.0.0-SNAPSHOT #553
Vulcan 2.6.4

**Comment by MWHunter** [comment]
Caused by https://github.com/retrooper/packetevents/issues/240

**Comment by MWHunter** [comment]
Will be fixed in next release as a packetevents commit has fixed this.
