### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lordhadow1** [MWHunter/Grim#385]
**Describe the bug**
Error

**To Reproduce**
Error: https://paste.twerion.net/mikofomezu.lua

**Server Version:**
Latest Nacho 1.8.9

**Grim Version (Git commit or the version in the jar's name)**
Latest

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/bc3ecca571df91acf029a44a63fe7d53c02125e0
