### ISSUE TITLE
Boat colliding

### ISSUE THREAD

**Issue by LewUwU** [MWHunter/Grim#388]
**Describe the bug**
False-positive while colliding with a boat

**To Reproduce**
Collide a boat

**Client & Server Version:**
1.8.8

**Grim Version (Git commit or the version in the jar's name)**
2.2.2

**Relevant plugins**
Or all plugins if you are unsure

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/63b273d60da03db254a0014ccdde0eb21b05a50a
