### ISSUE TITLE
Movement False with knockback entchantment on swords

### ISSUE THREAD

**Issue by lordhadow1** [MWHunter/Grim#389]
**Describe the bug**
Movement false when fighting

**To Reproduce**
Jump while Fighting

https://youtu.be/9XwLEfGITgc (Lunar 1.8.9)
https://youtu.be/NUJ48EXqicw (LabyMod 1.8.9 with Doublejump)
https://youtu.be/G6r7hYxoCuk (Only Labymod 1.8.9)
 https://youtu.be/popnClNp1kk (1.8.9 Vanilla with FOV 60%)

**Server Version:**
Latest 1.8.9 Nacho

**Grim Version (Git commit or the version in the jar's name)**
2.2.3

**Comment by MWHunter** [comment]
Closing as should be fixed by https://github.com/retrooper/packetevents/commit/049f5f412333f98758606190ba57d6e38a21daae
