### ISSUE TITLE
Grim clips players through the virtual (packet) world border

### ISSUE THREAD

**Issue by VidTu** [MWHunter/Grim#397]
**Describe the bug**
Grim (force-)clips players through the **packet** world border.

**To Reproduce**
1. Join the server.
2. Send a packet (virtual) world border. (example using [ProtocolLib on 1.18.2](https://gist.github.com/VidTu/26d631cc4d3da0fb502f1820404d6bed))
3. Jump into it.
4. Notice that the Grim clips you through the border.

[Video](https://www.youtube.com/watch?v=MH2JvT6sFo4)

**Server Version:**
Purpur 1.18.2 [git-Purpur-1609 (MC: 1.18.2)]

**Grim Version (Git commit or the version in the jar's name)**
2.2.5

**Relevant plugins**
Any plugins, that send packet world borders.

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/904e6685861b4228f892d1387fd0f6088761b59a
