### ISSUE TITLE
1.8 clients would theoretically break the movement checks due to a bukkit feature

### ISSUE THREAD

**Issue by MWHunter** [MWHunter/Grim#40]
The lastX, lastY, and lastZ would be overwritten when the vanilla 1.8 client sends their regular movement packet every tick, and bukkit would skip over the move event because the client did not move enough.  We don't intentionally support 1.8 clients but there's no reason to try and break them due to bad anticheat design.

Not sure if this would actually break anything, but it might and it's bad to have hidden issues.

**Comment by MWHunter** [comment]
The fix is planned in the transition to a fully packet-based anticheat.  I wonder if I can not touch the bukkit API at all, other than in the main class.

**Comment by terminalsin** [comment]
1.8 has completely different collisions which are in theory much simpler and much faster (no idea why these were changed). 

Such system impacts from 1.7-1.12.2. Unless you find a way to mix both, which I don’t recommend, I suggest using interfaces for different method types such as entity tick and living tick.
