### ISSUE TITLE
Creative doorway simulation & position place falses

### ISSUE THREAD

**Issue by kixmc** [MWHunter/Grim#401]
**Describe the bug**
In creative mode, repeatedly opening any sort of door with a frame around it while holding a block falses position place. And, when using a setup as shown with fences I false simulation and unable to pass through the door on both sides only after position place falses. I do not false simulation after falsing position place if there are no fences, and I do not false position place with an empty hand

**To Reproduce**
1) Ensure you are in creative mode - this issue is not present using survival
2) Create a setup as shown: [https://i.imgur.com/Sc5EBMN.png](https://i.imgur.com/Sc5EBMN.png)
3) Open and close the door while holding a block until you fail position place
4) Attempt to walk through the doorway

Debug: [https://paste.gg/p/anonymous/b9c06e396b2344c183fb69a37ceff0cc](https://paste.gg/p/anonymous/b9c06e396b2344c183fb69a37ceff0cc)

**Server Version:**
1.18.2 purpur

**Grim Version (Git commit or the version in the jar's name)**
Compiled today from source

**Relevant plugins**
n/a

**Comment by MWHunter** [comment]
This should be fixed by https://github.com/retrooper/packetevents/commit/d69ad9ef9ad576706ead09f306cb6e56847d44c5 as wrappedblockstates were entirely broken.
