### ISSUE TITLE
Grim interfering with hologram packets using hex colors

### ISSUE THREAD

**Issue by kixmc** [MWHunter/Grim#402]
**Describe the bug**
When Grim is installed, holograms / invisible armor stands with always visible nametags have their hex colors improperly displayed.

**To Reproduce**
1) Create a hologram on a server without Grim installed using `/dh create test #eeaf61Hex text`
2) The hologram displays the hex color correctly. Now install Grim
3) The hologram displays hex incorrectly

**Server Version:**
1.18.2 purpur

**Grim Version (Git commit or the version in the jar's name)**
Compiled today

**Relevant plugins**
[DecentHolograms](https://www.spigotmc.org/resources/decent-holograms-1-8-1-18-2-papi-support-no-dependencies.96927/)

**Comment by MWHunter** [comment]
Grim no longer re-encodes this packet for players other than the player itself.
