### ISSUE TITLE
False positive when towering with end rods

### ISSUE THREAD

**Issue by Jaren8r** [MWHunter/Grim#404]
https://user-images.githubusercontent.com/8620569/163709290-6155636f-da5e-4588-8b3f-ad6777f38f0a.mp4

**Comment by Ayazerzurum2** [comment]
In addition, bridging with them does the same.

**Comment by MWHunter** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/d69ad9ef9ad576706ead09f306cb6e56847d44c5
