### ISSUE TITLE
Reach Falsing while in creative and no hacks

### ISSUE THREAD

**Issue by Illumes** [MWHunter/Grim#406]
**Describe the bug**
While on version 1.8 on lunar client and spigot 1.8 I false flag reach while in creative mode

**To Reproduce**
Video is preferred.   If video is not possible, for bypasses, the hacked client name, version, module, module settings, and the check being bypassed is enough.  For false positives, steps to reproduce is fine also.

**Server Version:**
1.8

**Grim Version (Git commit or the version in the jar's name)**
Grim 2.2.5-all but a beta version in the discord on 04/15/2022 removing animations from post checks

**Relevant plugins**
Or all plugins if you are unsure
The plugins that i have on the server are aquacore, viaversion, viarewind, and placeholderapi with grim ofc

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/f84a2049e2181ac51d765f9e9e7e36ac82f49aa0
