### ISSUE TITLE
Delay when mounting players on throwables

### ISSUE THREAD

**Issue by kixmc** [MWHunter/Grim#408]
**Describe the bug**
We have a plugin that listens for enderpearl throw and mounts the player on it. It takes about a solid second for the player to mount the pearl after throwing while Grim is installed. Without Grim, the mounting is instant

**To Reproduce**
1) Install [Rideable Enderpearl](https://www.spigotmc.org/resources/rideableenderpearl.72042/)
2) Throw a pearl with and without Grim installed. Take note of mount delay after throwing

**Server Version:**
1.18.2 purpur

**Grim Version (Git commit or the version in the jar's name)**
Latest from github

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/db2e5c1583a607b7bb475534685530775daa971a
