### ISSUE TITLE
Jumping on a cake while right clicking at it

### ISSUE THREAD

**Issue by ZugPilot** [MWHunter/Grim#409]
**Describe the bug**

This false positive/bug false flags you for simulation and ground spoof.

**To Reproduce**
Video is preferred.   If video is not possible, for bypasses, the hacked client name, version, module, module settings, and the check being bypassed is enough.  For false positives, steps to reproduce is fine also.

I tested this on vanilla 1.8.9, no clue if this also happens on different versions.
You right click a cake while jumping on it and you get flagged for simulation and ground spoof.
I right clicked both with an empty hand and with stone in my hand. It didn't change the outcome.

**Server Version:**
1.18.2 (test.grim.ac)

**Grim Version (Git commit or the version in the jar's name)**
2.2.5

**Relevant plugins**
Or all plugins if you are unsure
I tested on test.grim.ac

**Comment by MWHunter** [comment]
affects 1.18.2 clients too

**Comment by MWHunter** [comment]
https://github.com/MWHunter/Grim/commit/34e92f8e9dc07c53cf342ecd1b92ad71fc3e992c
