### ISSUE TITLE
False positive with slime blocks and slabs

### ISSUE THREAD

**Issue by ZugPilot** [MWHunter/Grim#412]
**Describe the bug**

The videos are the description.

**To Reproduce**
Video is preferred.   If video is not possible, for bypasses, the hacked client name, version, module, module settings, and the check being bypassed is enough.  For false positives, steps to reproduce is fine also.

Tested on vanilla 1.8.9 on test.grim.ac
Edit: This also works on 1.18.2

https://www.youtube.com/watch?v=aqx58jdJ-hw (without debug)
https://youtu.be/r0c3r7tIqUE (with debug)

**Server Version:**
1.18.2

**Grim Version (Git commit or the version in the jar's name)**
2.2.6

**Relevant plugins**
Or all plugins if you are unsure
tested on test.grim.ac

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/issues/434 or https://github.com/MWHunter/Grim/issues/439
