### ISSUE TITLE
False positives with ladders and trapdoors on 1.8.9 clients

### ISSUE THREAD

**Issue by ZugPilot** [MWHunter/Grim#414]
**Describe the bug**

False positives with ladders and trapdoors (see video for better description)
Tested on 1.18.2 and 1.8.9 and it only worked on the latter.

**To Reproduce**
Video is preferred.   If video is not possible, for bypasses, the hacked client name, version, module, module settings, and the check being bypassed is enough.  For false positives, steps to reproduce is fine also.

https://www.youtube.com/watch?v=PDEJOtNWlJ8

**Server Version:**
1.18.2

**Grim Version (Git commit or the version in the jar's name)**
2.2.6

**Relevant plugins**
Or all plugins if you are unsure
tested on test.grim.ac

**Comment by MWHunter** [comment]
Fixed in https://github.com/MWHunter/Grim/commit/e9b43846f1d7661f373f3242dff225e38900b635
