### ISSUE TITLE
Phase/Simulation false positive when walking into a glass pane + glass block (1.8)

### ISSUE THREAD

**Issue by iFlamingoz** [MWHunter/Grim#415]
**Describe the bug**
Phase and simulation falses whenever a player walks into a glass pane that is next to a glass block.

**To Reproduce**
https://youtu.be/QbI2uQYkGMM

**Server Version:** 1.8.8

**Grim Version:** 2.2.6

**Comment by MWHunter** [comment]
Fixed with https://github.com/MWHunter/Grim/commit/c8b6c94a6c4f74b6de74e0bf82671e793704820c
