### ISSUE TITLE
BadPacketsJ/Simulation false positives when riding entities (1.8)

### ISSUE THREAD

**Issue by iFlamingoz** [MWHunter/Grim#416]
**Describe the bug**
BadPacketsJ falses whenever a player is on an entity.
Simulation falses whenever a player exits an entity.

**To Reproduce**
https://youtu.be/hmM0xNODHJE

**Server Version:** 1.8.8

**Grim Version:** 2.2.6

**Comment by MWHunter** [comment]
Unable to reproduce the BadPacketsJ issue.  What client are you on?

**Comment by MWHunter** [comment]
Found an issue in packetevents that is likely was the cause https://github.com/retrooper/packetevents/commit/9d0dc9f06d0fcd92f20f4ab8ccf328140d1d6574

**Comment by iFlamingoz** [comment]
> Unable to reproduce the BadPacketsJ issue. What client are you on?

in case you still need this, I was using Lunarclient 1.8.9.
The simulation check doesn't false repetitively.

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/29bbe5a42ba5f598d52c8cfbb383d48998e26d44 and
