### ISSUE TITLE
Join error

### ISSUE THREAD

**Issue by Illumes** [MWHunter/Grim#417]
**Describe the bug**
I open my server and try to join with the client version 1.7 and I get an error

**To Reproduce**
What I did was tested without grim on the server and I could join but when grim was active on the server I could not with this error in console [13:55:00] [Server thread/INFO]: com.mojang.authlib.GameProfile@6c04e61b[id=<null>,name=j31,properties={},legacy=false] (/127.0.0.1:50861) lost connection: Disconnected
and a error from client Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Key was smaller than nothing! Weird key!

**Server Version:**
1.8.8

**Grim Version (Git commit or the version in the jar's name)**
2.2.6

**Relevant plugins**
ViaVersion, ViaRewind, Protocollib, and PlaceholderAPI

**Comment by MWHunter** [comment]
https://github.com/retrooper/packetevents/issues/339

**Comment by MWHunter** [comment]
Assuming that this was fixed as the adventure code in packetevents was refactored and it seems to work for me.  Re-open the issue if this is still an issue.
