### ISSUE TITLE
Skeleton Horse in Water false

### ISSUE THREAD

**Issue by scarfacered** [MWHunter/Grim#418]
**Describe the bug**
Riding Skeleton Horse (with saddle) in water falses Simulation

**Server Version:**
1.18.2

**Grim Version (Git commit or the version in the jar's name)**
Grim 2.2.6

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/3ede68e5961bf753dcb7a37e460821291ce0a8e6
