### ISSUE TITLE
BadPacketsF false positive on instant respawn (1.8)

### ISSUE THREAD

**Issue by iFlamingoz** [MWHunter/Grim#419]
**Describe the bug**
BadPacketsF falses after getting instantly respawned.

**To Reproduce**
https://youtu.be/LVQ3AEgpDHY
Used 1.8.9 LunarClient.

**Server Version:** 1.8.8

**Grim Version:** 2.2.6

**Comment by iFlamingoz** [comment]
This also happens when changing worlds.

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/0390fcc3ba22030c2602c7d900b17ec3477b2cee
