### ISSUE TITLE
False positive with sprint toggling

### ISSUE THREAD

**Issue by ZugPilot** [MWHunter/Grim#421]
**Describe the bug**

The video describes the bug.

**To Reproduce**
Video is preferred.   If video is not possible, for bypasses, the hacked client name, version, module, module settings, and the check being bypassed is enough.  For false positives, steps to reproduce is fine also.

https://youtu.be/BPTXblc-w_Y
https://youtu.be/7K6W4hF5LRw

**Server Version:**
1.18.2

**Grim Version (Git commit or the version in the jar's name)**
2.2.7

**Relevant plugins**
Or all plugins if you are unsure
tested on test.grim.ac

**Comment by MWHunter** [comment]
this was from me screwing with grim's sprinting code on the test server and isn't on the github or the spigot jar.  I'll continue playing with this.
