### ISSUE TITLE
False PositionPlace

### ISSUE THREAD

**Issue by InboundHalo** [MWHunter/Grim#426]
When you rightclick a stair standing in a position it makes grim think I am cheating. This also happens when you are in a netherportal and right-click the side of the portal while in another portal

![image](https://user-images.githubusercontent.com/78378380/164325938-6a3abd18-13a5-42b4-843e-3508c79073f0.png)
**Server Version:**
1.18.2
**Grim Version (Git commit or the version in the jar's name)**
2.2.6

**Relevant plugins**
![image](https://user-images.githubusercontent.com/78378380/164325975-2343b430-eeb1-420c-a1de-6d7891ae8d61.png)

**Comment by MWHunter** [comment]
stairs issue fixed in 2.2.7

**Comment by MWHunter** [comment]
portal bounding boxes fixed in https://github.com/MWHunter/Grim/commit/6a45af26f016475349569b1c5a194bffbc60d444
