### ISSUE TITLE
Bug false with slab hard to reproduce

### ISSUE THREAD

**Issue by Illumes** [MWHunter/Grim#434]
**Describe the bug**
The bug isn't consistent but it flagged when I was walking on a slab on a 1.8 server I was flying around for a little but I don't know if that could have caused it. It flagged simulation and ground spoof we also walked on other blocks and it flagged but it could have been a bugged block

**To Reproduce**
Video is preferred.   If video is not possible, for bypasses, the hacked client name, version, module, module settings, and the check being bypassed is enough.  For false positives, steps to reproduce is fine also.

**Server Version:**
1.8

**Grim Version (Git commit or the version in the jar's name)**
2.2.8 

**Relevant plugins**
All

**Comment by MWHunter** [comment]
Probably fixed by https://github.com/MWHunter/Grim/commit/9c5ef64bd72037cbeb4b148359270f19d182aa6d
