### ISSUE TITLE
false positive with (iron) doors

### ISSUE THREAD

**Issue by ZugPilot** [MWHunter/Grim#435]
**Describe the bug**

simulation false positive with iron doors, haven't tested with other types
tested on 1.18.2 vanilla

**To Reproduce**
Video is preferred.   If video is not possible, for bypasses, the hacked client name, version, module, module settings, and the check being bypassed is enough.  For false positives, steps to reproduce is fine also.

https://www.youtube.com/watch?v=WaUU4w8vmbI
A right clicked at the door with around 5 cps, this seems to have an affect on the false positive

**Server Version:**

1.18.2

**Grim Version (Git commit or the version in the jar's name)**

2.2.8 (?)

**Relevant plugins**
Or all plugins if you are unsure
tested on test.grim.ac

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/5a928c52f30fd4fb6f1a5addea6973f227b2d02e
