### ISSUE TITLE
False positive with iron door collisions

### ISSUE THREAD

**Issue by ZugPilot** [MWHunter/Grim#440]
**Describe the bug**

A false positive it is.

**To Reproduce**
Video is preferred.   If video is not possible, for bypasses, the hacked client name, version, module, module settings, and the check being bypassed is enough.  For false positives, steps to reproduce is fine also.

https://www.youtube.com/watch?v=oTetrywvBUA

**Server Version:**

1.18.2

**Grim Version (Git commit or the version in the jar's name)**

2.2.9

**Relevant plugins**
Or all plugins if you are unsure
tested on test.grim.ac

**Comment by MWHunter** [comment]
fixed by https://github.com/MWHunter/Grim/commit/db8a1a8ac79da6b32079993682281cbaec6231f3
