### ISSUE TITLE
Simulation false positive with toggling flight + going backwards (1.7)

### ISSUE THREAD

**Issue by iFlamingoz** [MWHunter/Grim#444]
**Describe the bug**
Simulation falses when a 1.7.10 player toggles flight and walks backwards.
I used the 1.7.10 Lunar client.

**To Reproduce**
https://youtu.be/w3fzKJwIW-I

**Server Version:** 1.8.8 NachoSpigot

**Grim Version (Git commit or the version in the jar's name)** 2ccaaab

**Relevant plugins**
Or all plugins if you are unsure

**Comment by MWHunter** [comment]
should be fixed by https://github.com/MWHunter/Grim/commit/5b0a2046b8645203cdf8b2547a5a32adebeb122e
