### ISSUE TITLE
Velocity spam against walls causing velocity/simulation false positives

### ISSUE THREAD

**Issue by iFlamingoz** [MWHunter/Grim#446]
**Describe the bug**
Velocity/simulation falses when velocity is spammed on a player against a wall.

**To Reproduce**
https://youtu.be/xF6j0MJqKwo

**Server Version:** 1.8.8 NachoSpigot

**Grim Version (Git commit or the version in the jar's name)** 72efe17a

**Relevant plugins**

**Comment by MWHunter** [comment]
Still an issue?

**Comment by iFlamingoz** [comment]
> Still an issue on latest git?

Yes.

**Comment by iFlamingoz** [comment]
> > Still an issue on latest git?
> 
> Yes.

Actually, it doesn't seem to flag as much anymore.

**Comment by MWHunter** [comment]
Seems fixed by https://github.com/MWHunter/Grim/commit/cd42f34c86d67725d7edf5aa54a16a4d8381ea2c

Re-open the issue if it isn't fixed

**Comment by iFlamingoz** [comment]
The issue isn't fixed and I can't seem to reopen the issue as you were the one to close it.

> Seems fixed by [cd42f34](https://github.com/MWHunter/Grim/commit/cd42f34c86d67725d7edf5aa54a16a4d8381ea2c)
> 
> Re-open the issue if it isn't fixed

**Comment by FlamWy** [comment]
I might be a little late in saying this but you also need to be suspended midair for this to false flag.
https://youtu.be/1LeMFCNDdIk

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/ae3ed1d638b4ab56d7f6a861b7b68dc72ed157b1
