### ISSUE TITLE
Grim Misc

### ISSUE THREAD

**Issue by Hyronymos1337** [MWHunter/Grim#448]
**Describe the bug**

**To Reproduce**
https://www.youtube.com/watch?v=vJqUSVK78qc

**Server Version:**
1.18.2

**Grim Version (Git commit or the version in the jar's name)**
latest git

**Relevant plugins**
Or all plugins if you are unsure

**Comment by MWHunter** [comment]
also affects weeping vines and fire

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/4d973d341b908233d900bf7c0b081b3ac90fda8a
