### ISSUE TITLE
Simulation false positives when shifting over the edges of blocks  (1.8)

### ISSUE THREAD

**Issue by iFlamingoz** [MWHunter/Grim#450]
**Describe the bug**
Simulation falses when a player sneaks over an edge of a block.

**To Reproduce**
https://youtu.be/sbt7IStd9VA
~~https://youtu.be/tCieypkaRd0~~

**Server Version:** 1.8.8

**Grim Version (Git commit or the version in the jar's name)** https://github.com/MWHunter/Grim/commit/72efe17a4a90488bb0cf6d572ca9376634d4c3f7

**Relevant plugins**
Or all plugins if you are unsure

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/5fd05e2f0a04e2268c8ddb491a4956ada9079593
