### ISSUE TITLE
Grim false-flags sneak-sprint-jumping with 1.14.4 client (on 1.18.2 server)

### ISSUE THREAD

**Issue by VidTu** [MWHunter/Grim#451]
**Describe the bug**
Grim false-flags jumping and sprinting, while sneaking with 1.14.4 client (on 1.18.2 server).

**To Reproduce**
1. Install ViaVersion and ViaBackwards on a 1.18.2 Paper server.
2. Join with the 1.14.4 client.
3. Start spamming sneak button, while sprinting and jumping.
4. Notice the false-flags.

https://www.youtube.com/watch?v=DlZDjawNE9s

**Server Version:**
1.18.2

**Grim Version (Git commit or the version in the jar's name)**
2.2.9

**Relevant plugins**
ViaVersion, ViaBackwards

Possibly related to #379

**Comment by MWHunter** [comment]
Related to https://github.com/MWHunter/Grim/issues/374 and https://github.com/MWHunter/Grim/issues/450

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/5fd05e2f0a04e2268c8ddb491a4956ada9079593
