### ISSUE TITLE
Cross-dimensional teleport while riding a vehicle false-flag

### ISSUE THREAD

**Issue by VidTu** [MWHunter/Grim#453]
**Describe the bug**
Taking knockback after cross-dimensional teleport while riding a vehicle false-flags Simulation.

**To Reproduce**
1. Enter a vehicle.
2. Perform a cross-dimensional teleport.
3. Take knockback from damage.

https://youtu.be/cmcDVs2WSfs

**Server Version:**
1.18.2 Paper

**Grim Version (Git commit or the version in the jar's name)**
2.2.9

**Relevant plugins**
(None)

**EDIT:** Apparently, you don't need to be in the vehicle at the moment of teleport. You just can enter/exit the vehicle, then teleport to another dimension and take knockback.

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/a08ea670b868535221167832e9d4dea43ff934a7
