### ISSUE TITLE
Killing a (living-entity) vehicle false-flags and throws console exception

### ISSUE THREAD

**Issue by VidTu** [MWHunter/Grim#457]
**Describe the bug**
Killing the living entity you riding false-flags for aim.

**To Reproduce**
1. Join the server via 1.18.2 client.
2. Ride a pig.
3. Kill the pig via splash potions. (while riding it)
4. Notice the false-flags and console errors.

Video: https://www.youtube.com/watch?v=rZy4ng-77BM
Error log: https://paste.gg/p/VidTu/662245aae19a4f1b8c85caf6128fea55

**Server Version:**
Paper 1.18.2

**Grim Version (Git commit or the version in the jar's name)**
[3930c9a](https://github.com/MWHunter/Grim/commit/3930c9aeebb12d0d509851d83823815a873f9fa4)

**Relevant plugins**
None

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/344f621e91c29b292ece260696656c0ca1dd9524
