### ISSUE TITLE
AimDuplicate false on teleport (1.8)

### ISSUE THREAD

**Issue by iFlamingoz** [MWHunter/Grim#459]
**Describe the bug**
AimDuplicate falses when teleporting with a different yaw/patch value to what the player has. 

**To Reproduce**
'/tp ign ~ ~ ~ diffPitch diffYaw'

**Server Version:** 1.8.8 NachoSpigot

**Grim Version (Git commit or the version in the jar's name)** https://github.com/MWHunter/Grim/commit/0a4318b5ff993ce665139e76c5e5b3b88bc8e29d

**Relevant plugins**
Or all plugins if you are unsure

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/8aba718df897701d86ab14468ad54731f72db175
