### ISSUE TITLE
Many non-solid blocks acting like solid blocks on 1.16

### ISSUE THREAD

**Issue by Jyguy** [MWHunter/Grim#477]
**Describe the bug**
Many non-solid blocks (e.g. doors, tall grass, flowers, vines) are handled like solid blocks by the anticheat, making the anticheat think that the player is walking through solid blocks, causing flags. It can also cause random client-side ghost blocks to be formed around the player (in the clip, red wool, but other blocks can also form such as [fire](https://i.imgur.com/TL2DKpt.png)). Right-clicking these ghost blocks updates the block to what it was before.

This only happens on a 1.16 server. 1.17+ and <=1.15 are unaffected.

**To Reproduce**
https://www.youtube.com/watch?v=UwvMscc2ghk

**Server Version:**
This server is running Paper version git-Paper-"fa1a7c180" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Grim Version (Git commit or the version in the jar's name)**
2.2.11

**Relevant plugins**
Plugins (1): GrimAC

**Comment by MWHunter** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/c4798df9dc1d6326ea134330e3aa2a0c836bafba
