### ISSUE TITLE
Climbing ladders has broken once again

### ISSUE THREAD

**Issue by MWHunter** [MWHunter/Grim#48]
The code is there it's just not running

**Comment by terminalsin** [comment]
Sometimes ladders will do this due to a collidedHorizontally issue.

**Comment by MWHunter** [comment]
Fixed by removing some debug I left in while refactoring the predictions.  

My system doesn't know the difference between colliding horizontally or pressing jump.  It doesn't matter, it just knows when it is possible to do either and sets the ladder velocity variable in case the player's velocity on the next tick is closer to the climbing velocity after possible inputs rather than the non-climbing velocity after possible inputs.

It does the same thing with a few other things too.
