### ISSUE TITLE
False positive when right-clicking with a placeable inside a passable block

### ISSUE THREAD

**Issue by Jyguy** [MWHunter/Grim#480]
**Describe the bug**
When inside blocks like tall grass, cobwebs, peony, sugar cane, signs, buttons, and possibly others, you can false flag PositionPlace every time you right click with any placeable. This includes seeds, redstone, and rails.

**To Reproduce**
https://www.youtube.com/watch?v=sauFOwoi2hk

**Server Version:**
This server is running Paper version git-Paper-"cc43ba7" (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc43ba7 on ver/1.17.1)
Also reproducible on other versions

**Grim Version (Git commit or the version in the jar's name)**
e34f961ee2d0ca8bd8d960442875125b18278eef

**Relevant plugins**
Plugins (1): GrimAC

**Comment by MWHunter** [comment]
Thanks for the report, fixed by https://github.com/MWHunter/Grim/commit/51a9506493fafa503d0656d0f892fda4f5392128
