### ISSUE TITLE
[False Positive] Sprinting whilst in a boat will cause you to flag once exiting the boat

### ISSUE THREAD

**Issue by MrMcyeet** [MWHunter/Grim#489]
**Describe the bug**
Starting sprinting whilst moving in a boat will cause you to flag once you exit the boat and move

**To Reproduce**
[Video](https://youtu.be/IthP4H41990)

1. Get into a boat and once moving, press ctrl (sprint)
2. Once your boat is against land, press shift (exit the boat) and move, and you'll flag

**Server Version:**
1.17.1 (Both client & server)

**Grim Version (Git commit or the version in the jar's name)**
2.2.12 (grimac-2.2.12-all.jar)

**Relevant plugins**
Grim and luckperms were the only things installed

**Comment by MWHunter** [comment]
Great, the client never actually sends that it starts sprinting.  That's another sprinting desync to put on the list.  I have no clue how to fix this.

**Comment by MWHunter** [comment]
Duplicate https://github.com/MWHunter/Grim/issues/379
