### ISSUE TITLE
Simulation false positives when colliding with the world border

### ISSUE THREAD

**Issue by iFlamingoz** [MWHunter/Grim#492]
**Describe the bug**
Simulation false positives when colliding with the world border, however updating the world border with '/worldborder set' fixes it.

**To Reproduce**
https://youtu.be/APNFZ1Wzm6o

**Server Version:** 1.8.8

**Grim Version (Git commit or the version in the jar's name)** 6f64c7542761e4c402f21a885a78dcd7d97b1dae

**Relevant plugins**
Or all plugins if you are unsure

**Comment by MWHunter** [comment]
https://github.com/MWHunter/Grim/commit/1a83c65adce0f20d40970dcf4de2f9e387fec69a

**Comment by iFlamingoz** [comment]
> [1a83c65](https://github.com/MWHunter/Grim/commit/1a83c65adce0f20d40970dcf4de2f9e387fec69a)

Issue persists on the newest commit.

**Comment by iFlamingoz** [comment]
Fixed with https://github.com/MWHunter/Grim/commit/f88ef6f82847b73825dac83551dcf432e7e4d0ba
