### ISSUE TITLE
Riptide bypass

### ISSUE THREAD

**Issue by Pantera07** [MWHunter/Grim#497]
**Describe the bug**
Riptide trident use without water and rain

**To Reproduce**
meteor
https://youtu.be/PuGSjeXzcsc

**Server Version:**
GrimAC Official Server (2022-05-20)

**Grim Version (Git commit or the version in the jar's name)**
GrimAC Official Server (2022-05-20)

**Relevant plugins**
GrimAC Official Server (2022-05-20)

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/dd19202221cbcc91ef15f658bc546acf4b5eb7aa
