### ISSUE TITLE
[False] Looking down while gliding (C1.12.2 -> S1.18.2)

### ISSUE THREAD

**Issue by VidTu** [MWHunter/Grim#501]
**Describe the bug**
Looking straight down while flying with an elytra false-flags Grim.

**To Reproduce**
1. Join the 1.18.2 server with the 1.12.2 (vanilla) client.
2. Fly high enough with elytra.
3. Look straight down.

https://www.youtube.com/watch?v=EazcFVWtERw

**Server Version:**
Paper 1.18.2

**Grim Version (Git commit or the version in the jar's name)**
2.2.13

**Relevant plugins**
ViaVersion, ViaBackwards

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/dc19ac2a91dfe65fd36fef9893578ae66996b422
