### ISSUE TITLE
[False] Grim STILL false-flags on sneak-jumping (C1.14.4 -> S1.18.2)

### ISSUE THREAD

**Issue by VidTu** [MWHunter/Grim#502]
#451 is not fixed with the latest Grim version.

https://www.youtube.com/watch?v=MomHtlmf1mY

**Comment by MWHunter** [comment]
Can you reproduce on a vanilla client?  I know of a cheat client that flags this without modules because they messed up some code.

**Comment by VidTu** [comment]
It's a vanilla client, just a PolyMC launcher.

**Comment by VidTu** [comment]
Just reproduced with the vanilla launcher. https://www.youtube.com/watch?v=wg07FQmC914

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/54043c61b09a10390376493c025685beea225f58
