### ISSUE TITLE
False positive: PositionPlace in spectator mode

### ISSUE THREAD

**Issue by Avenred** [MWHunter/Grim#505]
**Describe the bug**
Right clicking whist in a block in spectator mode flags for PositionPlace 

**To Reproduce**
- Hold a block in hand
- Enter spectator mode (/gamemode spectator)
- Fly into a wall/inside of a block
- Right click while inside of a block

**Server Version:**
Purpur 1623 (1.18.2)

**Grim Version (Git commit or the version in the jar's name)**
grimac-2.2.13-all

**Relevant plugins**
N/A

**Comment by MWHunter** [comment]
Fixed by and duplicate of https://github.com/MWHunter/Grim/issues/480

**Comment by Avenred** [comment]
Oops, I didn't know that issue was related. Thanks for the fix!

**Comment by MWHunter** [comment]
I didn't know it was related either
