### ISSUE TITLE
Simulation False While Using a Bow Underwater

### ISSUE THREAD

**Issue by ADMCruncher** [MWHunter/Grim#507]
**Describe the bug**
Simulation false flag that happens when a player it hit with an arrow while crouching underwater.

**To Reproduce**
https://streamable.com/e6fse5
Note: An air pocket is not required for the flag.

**Server Version:**
Grim test server on 24-05-2022

**Grim Version (Git commit or the version in the jar's name)**
Grim test server on 24-05-2022

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/f5e0da4e6767c96b7b8e0cf9c003a41c4788b4b6
