### ISSUE TITLE
Building up causing Simulation false positives (1.8)

### ISSUE THREAD

**Issue by iFlamingoz** [MWHunter/Grim#508]
**Describe the bug**
Building up can cause Simulation to false positive.

**To Reproduce**
https://youtu.be/pJfP83qz5Rc

**Server Version:** 1.8.8

**Grim Version (Git commit or the version in the jar's name)** 6faeb22c8e20a11d43da90b33abdb706ad6a0fb5

**Relevant plugins**
This also occurs on the test server.

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/b0145ad074b176d86314711f1a68b874093d6b72
