### ISSUE TITLE
[FALSE] Walking on/off bed

### ISSUE THREAD

**Issue by booky10** [MWHunter/Grim#509]
**Describe the bug**
Walking on or off a bed (to another block) causes a false flag.

**To Reproduce**
https://youtu.be/RIqpQ1LQNfo

**Server Version:**
`test.grim.ac`

**Grim Version (Git commit or the version in the jar's name)**
`test.grim.ac`

**Relevant plugins**
None

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/c903a2fed96d8bdf9c2424891f930804ffb2d791
