### ISSUE TITLE
[FALSE] Breaking bed while walking on it

### ISSUE THREAD

**Issue by booky10** [MWHunter/Grim#510]
**Describe the bug**
Walking on a bed while breaking it flags.
Could be caused by the delay between destruction of the two parts or blipping up on the not broken part.

**To Reproduce**
https://youtu.be/ZVv_6gYS7mU

**Server Version:**
`test.grim.ac`

**Grim Version (Git commit or the version in the jar's name)**
`test.grim.ac`

**Relevant plugins**
None

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/c903a2fed96d8bdf9c2424891f930804ffb2d791
