### ISSUE TITLE
[FALSE] Walking on slime (with slabs in between)

### ISSUE THREAD

**Issue by booky10** [MWHunter/Grim#511]
**Describe the bug**
Walking on slime (with slabs in between) will false.

**To Reproduce**
![somepicturetextidkwhattoputhere](https://user-images.githubusercontent.com/53302036/170351612-ee459d82-01ae-4748-9e49-56313271ec24.png)
https://youtu.be/kn0_NaC8u1U

**Server Version:**
`test.grim.ac`

**Grim Version (Git commit or the version in the jar's name)**
`test.grim.ac`

**Relevant plugins**
None

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/c903a2fed96d8bdf9c2424891f930804ffb2d791
