### ISSUE TITLE
Scaffolding clutch and floor vanish

### ISSUE THREAD

**Issue by Portal2001** [MWHunter/Grim#512]
**Describe the bug**
when clutching with Scaffolding it gives false then floor vanish

**To Reproduce**
Scaffolding clutch fall in between 2

https://user-images.githubusercontent.com/74851280/170564084-5e655cb4-a4df-4aca-8c47-29ff367b2248.mp4

**Server Version:**
1.18.2
**Grim Version (Git commit or the version in the jar's name)**
grimac test server on 27-05-2022
**Relevant plugins**
none

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/6f2856af8ac2a420eb9f7766528b0ede1d76118b

The block disappearing thing was fixed a few days ago, I just didn't update the test server immediately
