### ISSUE TITLE
[FALSE] Placing blocks while inside block

### ISSUE THREAD

**Issue by booky10** [MWHunter/Grim#513]
**Describe the bug**
If your head position is inside a block (e.g. tall grass or a two high flower such as lilac) you can't place any blocks, even though vanilla allows such a behavior.

**To Reproduce**
https://youtu.be/aY0mImnsATc

**Server Version:**
`test.grim.ac`

**Grim Version (Git commit or the version in the jar's name)**
`test.grim.ac`

**Relevant plugins**
None

**Comment by MWHunter** [comment]
Duplicate
