### ISSUE TITLE
GrimAC does not detect crystal auras from Meteor client.

### ISSUE THREAD

**Issue by CrushedKingoros** [MWHunter/Grim#515]
**Describe the bug**
GrimAC does not detect crystal auras from Meteor clients.

**To Reproduce**
Detonate an end crystal using the Meteor Client's default config crystal aura.

https://user-images.githubusercontent.com/77001498/170824323-d3f46539-aaf4-43e0-8f1e-85c6bbb1fee0.mp4

**Server Version:**
1.18.2 papermc latest (git-Paper-350)

**Grim Version (Git commit or the version in the jar's name)**
grimac-2.2.14-all (i downloaded this from official discord.)

**Relevant plugins**
Or all plugins if you are unsure
grimac and protocolib

**Comment by CrushedKingoros** [comment]
Also, the fastplace module of the Meteor client is not detected either.

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/7e5c832f6cd1f9d5e8ce4ecccf40ff6dfe5df9e4

I don't care about fastplace, it isn't doing anything incorrectly, it just is clicking fast
