### ISSUE TITLE
GrimAC does not detect vertical scaffold from Bleachhack.

### ISSUE THREAD

**Issue by CrushedKingoros** [MWHunter/Grim#516]
**Describe the bug**
GrimAC doesn't block Bleachhack's vertical scaffolding. (not horizontal)

**To Reproduce**
https://user-images.githubusercontent.com/77001498/170831193-810ff19a-63b3-431a-8287-97e875252fd1.mp4
![image](https://user-images.githubusercontent.com/77001498/170831208-7e952ad2-9d11-403d-a2ba-94676da4feff.png)
Use this config to bypass using a vertical scaffold.

Server Version:
1.18.2 papermc latest (git-Paper-350)

Grim Version (Git commit or the version in the jar's name)
grimac-2.2.14-all (i downloaded this from official discord.)

Relevant plugins
Or all plugins if you are unsure
grimac and protocolib

**Comment by Ayazerzurum2** [comment]
Grim doesn't attempt to prevent scaffold whatsoever, they will be added later on.

**Comment by MWHunter** [comment]
Grim has scaffolding checks and will try to fix this

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/6b522fa2035eec43e1993f65a138219a31dfd15d to the point where it flags and seems to be as fast as normal towering
