### ISSUE TITLE
No Break Delay Bypass

### ISSUE THREAD

**Issue by DontNeedAName** [MWHunter/Grim#520]
**Describe the bug**
In vanilla theres a delay after breaking a block before you can start breaking the next block. There is currently no check to enforce that delay.

**To Reproduce**
Use aristois from aristois.net and turn on "No Delay" under the world category.

**Server Version:**
Paper 1.17.1

**Grim Version (Git commit or the version in the jar's name)**
2.2.14

**Comment by MWHunter** [comment]
Probably will be fixed whenever https://github.com/MWHunter/Grim/issues/221 gets fixed

Second oldest open grim issue

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/8f0d4b6384cd5b8f0b6019b49e750c90c456159c
