### ISSUE TITLE
Clientside-Placed Skulls False Positive in 1.8

### ISSUE THREAD

**Issue by amnoah** [MWHunter/Grim#526]
**Describe the bug**
Grim flags 1.8 players stepping on clientside-placed skulls.

**To Reproduce**
Launch 1.8, place any type of skull constantly at your feet in a WorldGuard protected area, watch the false flags roll in.
https://www.youtube.com/watch?v=3jOePqBYVj8
https://www.youtube.com/watch?v=OwDtE29BJPE

**Server Version:**
1.18.2 Purpur-1623

**Grim Version (Git commit or the version in the jar's name)**
2.2.15 Hotfix

**Relevant plugins**
test.grim.ac

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/ec3a82f04cf2e8f51a129f605c47c6b7a74e3bd1
