### ISSUE TITLE
High memory usage (memory leak?)

### ISSUE THREAD

**Issue by DontNeedAName** [MWHunter/Grim#528]
**Describe the bug**
So basically my server was lagging due to high gc times so i made a memory dump using spark and analyzed it using Eclipse memory analyzer and found out that the plugin uses a heck lot of memory. At least compared to what most other plugins use. I mean it makes sense for the fact that it recreates the entire world, but still maybe you could check if there is a way to optimize this.
![Screenshot 2022-06-02 200443](https://user-images.githubusercontent.com/50169271/171696994-c83cfc4c-4096-4c36-a0ad-cb2154318963.png)
![Screenshot 2022-06-02 200858](https://user-images.githubusercontent.com/50169271/171697667-c83d72f0-a693-4595-9c96-d51d5a43e37e.png)

**To Reproduce**
I can send you the full memory dump if you want.

**Server Version:**
git-Paper-409 (MC: 1.17.1)

**Grim Version (Git commit or the version in the jar's name)**
2.2.14

**Relevant plugins**
don't think there are any

**Comment by MWHunter** [comment]
Likely fixed by 2.2.16, if you were running ViaVersion

**Comment by DontNeedAName** [comment]
yeah thanks
