### ISSUE TITLE
piston false positive

### ISSUE THREAD

**Issue by Shwabbaa** [MWHunter/Grim#532]
**Describe the bug**
Standing on piston neck then retracting the piston adds some sort of velocity to the player

**To Reproduce**
https://youtu.be/bOCnj2z9Yq8

**Server Version:**
official test server

**Grim Version (Git commit or the version in the jar's name)**
official test server

**Relevant plugins**
official test server

**Comment by MWHunter** [comment]
Duplicate https://github.com/MWHunter/Grim/issues/498
