### ISSUE TITLE
PostCheck false

### ISSUE THREAD

**Issue by Hyronymos1337** [MWHunter/Grim#535]
**Describe the bug**
1.8 client on 1.18.2 server

**To Reproduce**
[Video is preferred.   If video is not possible, for bypasses, the hacked client name, version, module, module settings, and the check being bypassed is enough.  For false positives, steps to reproduce is fine also.](https://www.youtube.com/watch?v=OT7SGsFOCkY)

**Server Version:**
1.18.2 purpur

**Grim Version (Git commit or the version in the jar's name)**
lateste

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/00c3a66959167d44724f73a01fc7940576d70e7b
