### ISSUE TITLE
Grim flags only Simulation for AntiKnockback

### ISSUE THREAD

**Issue by VidTu** [MWHunter/Grim#536]
**Describe the bug**
Grim flags ONLY Simulation for AntiKnockback, though [Knockback](https://github.com/MWHunter/Grim/blob/e73d979494c9a285b673e0be0d698fe15101d2e6/src/main/resources/punishments/en.yml#L13) exists in default punishments config

**To Reproduce**
1. Use Timer from any client.
2. Notice that there are "Timer" flags in chat. (and in punishments config too)
3. Use Velocity/AntiKnockback from any client.
4. Notice that there are only "Simulation" flags in chat. (but there's "Knockback" configuration in punishments config)

https://www.youtube.com/watch?v=FeZuJ_NFknk (Meteor Client used in video)

**Server Version:**
Paper 1.18.2

**Grim Version (Git commit or the version in the jar's name)**
[fe7301b976e7c98e4e76f716898fbc7376a41036](https://github.com/MWHunter/Grim/tree/fe7301b976e7c98e4e76f716898fbc7376a41036)

**Relevant plugins**

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/b05005d339881eb7fa66f68d3c097d6d47cd4436
