### ISSUE TITLE
Reach Post Transactions not enabling

### ISSUE THREAD

**Issue by iFlamingoz** [MWHunter/Grim#542]
**Describe the bug**
Reach Post Transactions are not enabling as the path to check whether it's enabled or not is incorrect.
https://github.com/MWHunter/Grim/blob/2.0/src/main/java/ac/grim/grimac/manager/init/start/TickEndEvent.java#:~:text=getBooleanElse(%22-,reach,-.enable%2Dpost%2Dpacket

**To Reproduce**
![image](https://user-images.githubusercontent.com/35672743/172995072-bc5713a4-4005-4c88-ac13-55d2837d3bba.png)
![image](https://user-images.githubusercontent.com/35672743/172994885-e00584d9-9e0b-4b13-8ba0-e7c208d8d1a4.png)
![image](https://user-images.githubusercontent.com/35672743/172994911-55560103-0bc8-4691-89a6-b0866a78557d.png)

**Grim Version (Git commit or the version in the jar's name)** d63b6448daa40064c28aa530e038f9f7a6008298

**Comment by MWHunter** [comment]
should be fixed by https://github.com/MWHunter/Grim/commit/21a8447a1873cabd3c2015f6fdeb5f80b111dfcd although I didn't test
