### ISSUE TITLE
Elytra/Inventory false

### ISSUE THREAD

**Issue by ilovefuud** [MWHunter/Grim#547]
**Describe the bug**
Clientside I had an elytra equipped, Serverside I did not.
I would false when attempting to start elytra flying

**To Reproduce**
I'm not sure, I just did /i elytra on the test server, and put it on. I tried reproducing right clicking the item or shift clicking.

**Server Version:**
Test server

**Grim Version (Git commit or the version in the jar's name)**
Test server

**Comment by MWHunter** [comment]
duplicate https://github.com/MWHunter/Grim/issues/504
