### ISSUE TITLE
Not compatible with Aquacore

### ISSUE THREAD

**Issue by Abel156** [MWHunter/Grim#548]
**Describe the bug**

Players are not detected when the server uses aquacore

**To Reproduce**
Video is preferred.   If video is not possible, for bypasses, the hacked client name, version, module, module settings, and the check being bypassed is enough.  For false positives, steps to reproduce is fine also.

Using aquacore on your server requires no special skills

**Server Version:**

Foxspigot 1.8

**Grim Version (Git commit or the version in the jar's name)**

grimac-2.3.3-all

**Relevant plugins**
Or all plugins if you are unsure

Aquacore

**Comment by MWHunter** [comment]
Any exceptions?

**Comment by Abel156** [comment]
> 

Sorry I didn't understand what you were saying..
But it seems that as long as the server is running aquacore, there will be no detection of players

**Comment by ilovefuud** [comment]
> 

he is asking if there are any errors

**Comment by MWHunter** [comment]
Do you get kicked after 2 minutes for Timed Out!

**Comment by Abel156** [comment]
> Do you get kicked after 2 minutes for Timed Out!

It doesn't seem like it? Can you try it? I don't remember it getting kicked. Maybe
I don't have an accurate answer because I don't have access to a computer at the moment

**Comment by Abel156** [comment]
> Do you get kicked after 2 minutes for Timed Out!

But I remember if I was a staff when I entered the server aquacore would send the message xxx staff entered I remember that the message was re-sent a few minutes after I entered

**Comment by MWHunter** [comment]
Is this still an issue?

**Comment by MWHunter** [comment]
No response.  I can't do anything about it, AquaCore must be the ones not breaking grim.  Likely injector issue on their end.
