### ISSUE TITLE
flagged fast boatfly + automount

### ISSUE THREAD

**Issue by hellidox** [MWHunter/Grim#549]
**Describe the bug**
you can fly with boatfly and automount
**To Reproduce**
https://youtu.be/hlX_HNMvm-Y
using meteor:
turn on boatfly and auto mount
get off the ground 3 blocks should be fine
place boat
sprint, hold space, and look up
fly

**Server Version:**
test server
**Grim Version (Git commit or the version in the jar's name)**
test server

**Comment by MWHunter** [comment]
Duplicate https://github.com/MWHunter/Grim/issues/494
