### ISSUE TITLE
block disappeared on right-click after the speed bridge

### ISSUE THREAD

**Issue by Portal2001** [MWHunter/Grim#552]
**Describe the bug**
block disappeared on right-click after the speed bridge also placing any other block

**To Reproduce**

https://user-images.githubusercontent.com/74851280/173504389-321eb249-384a-424e-9d74-b1e5afce1085.mp4

**Server Version:**
1.18.2
**Grim Version (Git commit or the version in the jar's name)**
2.2.8 test server
**Relevant plugins**
none

**Comment by MWHunter** [comment]
able to reproduce on test server, unable to reproduce locally.  Weird.

**Comment by MWHunter** [comment]
Possibly related to https://github.com/MWHunter/Grim/issues/537

**Comment by MWHunter** [comment]
Test server specific, don't know what caused it but reinstalling the server seems to have fixed it
