### ISSUE TITLE
False while spamming sneak & jumping

### ISSUE THREAD

**Issue by Foulest** [MWHunter/Grim#553]
**Describe the bug**
Spamming sneak while jumping on 1.8.X versions.

**To Reproduce**
https://media.discordapp.net/attachments/811396971059085364/986411992963219546/javaw_jJ5xJFA18f.gif?width=995&height=523

**Server Version:**
Grim Test Server

**Grim Version (Git commit or the version in the jar's name)**
Grim Test Server

**Relevant plugins**
Grim Test Server

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/7a74e6be98c853b8849f6fc2cc817ae5c987b868

Caused by ViaRewind
