### ISSUE TITLE
Mangrove log break speed

### ISSUE THREAD

**Issue by TreeOfSelf** [MWHunter/Grim#554]
**Describe the bug**
Mangrove logs reappear after being broken with an efficiency axe

**To Reproduce**
https://www.youtube.com/watch?v=upJl8nrLq3M

**Server Version:**
Paper 1.19 Stable

**Grim Version (Git commit or the version in the jar's name)**
Grim Anticheat 2.3.4

**Relevant plugins**
None

**Comment by MWHunter** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/0ad3baeea44ecee60f914d65a92b7acb6b69d6c1
