### ISSUE TITLE
Chest boat collision

### ISSUE THREAD

**Issue by TreeOfSelf** [MWHunter/Grim#555]
**Describe the bug**
Chest boat collision off 

**To Reproduce**
https://youtu.be/Lsknbn-TL-E

**Server Version:**
Paper 1.19 

**Grim Version (Git commit or the version in the jar's name)**
Grim Anticheat 2.3.4

**Relevant plugins**

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/0ca5839c8ec09fed0307c060500f76e00b90f3e9
