### ISSUE TITLE
[2.3.5] PacketEvents caught an unhandled exception, default chest state is null

### ISSUE THREAD

**Issue by noiverre** [MWHunter/Grim#560]
**Describe the bug**
https://paste.gg/p/anonymous/10091997ee094a1c90c32bc3ba6b2807

**To Reproduce**
Update to 2.3.5 from 2.3.4 and join the server

**Server Version:**
This server is running Paper version git-Paper-14 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 48f7a1a)

**Grim Version (Git commit or the version in the jar's name)**
2.3.5

**Relevant plugins**
ProtocolLib v5.0.0-SNAPSHOT-b569
This server is running Geyser version 2.0.4-SNAPSHOT (git-master-aa097ec) (Java: 1.19, Bedrock: 1.19.0)

**Comment by MWHunter** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/bb27307e25c7d379b8085f2dd44a0fca6277c64d
