### ISSUE TITLE
Add more config about checks so that we can disable it

### ISSUE THREAD

**Issue by Radiation-pi** [MWHunter/Grim#561]
I tried to remove the fastblock check but failed because I am a code novice. 
To my honest, the config of grimAC is hard to understand and short, please add more config and notes if possible. I can learn how to disable some checks if you tell me what should I do.

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/41edf0b90a9af4e5d960dd570afc24f49b61fa81
