### ISSUE TITLE
GRIM VELOCITY

### ISSUE THREAD

**Issue by Abel156** [MWHunter/Grim#563]
**Describe the bug**

Velocity doesn't work? Not sensitive?
I reported this issue on github yesterday
Yet no one believed it and it was closed and not resolved
https://youtu.be/Egeul00zjKY

**To Reproduce**
Video is preferred.   If video is not possible, for bypasses, the hacked client name, version, module, module settings, and the check being bypassed is enough.  For false positives, steps to reproduce is fine also.

https://youtu.be/Egeul00zjKY

**Server Version:**

1.8

**Grim Version (Git commit or the version in the jar's name)**

grimac-2.3.6-all

**Relevant plugins**
Or all plugins if you are unsure

none

**Comment by Abel156** [comment]
_**Added: knockback setbackvl: -1**_
okay I only posted a picture yesterday but it's real

**Comment by Abel156** [comment]
> 
cool
will flag, this issue to be closed, thanks for your help (is this a config error...?)
:)

**Comment by ilovefuud** [comment]
#566
