### ISSUE TITLE
Lag spikes causing BadPacketP false positives

### ISSUE THREAD

**Issue by iFlamingoz** [MWHunter/Grim#565]
**Describe the bug**
Lag Spikes causing BadPacketP false positives.

**To Reproduce**
https://youtu.be/FbMn7S4iU2M

**Grim Version (Git commit or the version in the jar's name)** f1cc31ca4eb107b0bec179f8e190957e99e81caa

**Relevant plugins**
Or all plugins if you are unsure

**Comment by iFlamingoz** [comment]
Able to reproduce with a vanilla client.

**Comment by MWHunter** [comment]
Fixed by removing BadPacketsP

https://github.com/MWHunter/Grim/commit/755e95ca8d96ecce84142abd68f08e2483a86a22
