### ISSUE TITLE
server.properties bug

### ISSUE THREAD

**Issue by AVuTuVA** [MWHunter/Grim#567]
**Describe the bug**
If you create a world border through server.properties and run into it, then there will be false anti-cheat positives.

**To Reproduce**
They said not necessarily.

**Server Version:**
1.18.2

**Grim Version (Git commit or the version in the jar's name)** https://github.com/MWHunter/Grim/commit/f1cc31ca4eb107b0bec179f8e190957e99e81caa

**Relevant plugins**
Not required

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/f88ef6f82847b73825dac83551dcf432e7e4d0ba
