### ISSUE TITLE
Fence/Fence Gate False Positives

### ISSUE THREAD

**Issue by amnoah** [MWHunter/Grim#569]
**Describe the bug**
When placing/interacting with fences and fence gate blocks while moving into them Grim false flags.

**To Reproduce**
https://youtu.be/_DfGH0HoyOs (Sorry for the music on in the background)

**Server Version:**
test.grim.ac - 1.19

**Grim Version (Git commit or the version in the jar's name)**
test.grim.ac (2.3.6 I assume)

**Relevant plugins**
test.grim.ac

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/28a4cb41e068395c201ca3161b03b869e6773887
