### ISSUE TITLE
Anticheat doesn't reactivate checks immediately if permission grim.exempt was deleted, after rejoin everything is working fine

### ISSUE THREAD

**Issue by szmaLED** [MWHunter/Grim#571]
**Describe the bug**
Grim stops its checks immediately when permission grim.exempt is set. But after unsetting this permission, anticheat doesn't activate checks. It reactivate checks only after rejoining the server.

**To Reproduce**
- Use anything causing grim flags
- Check if flags are on
- Give player permission grim.exempt
- Flags are off
- Remove permission grim.exempt
- Flags are still off (should be on)
- Rejoin server
- Flags are on

**Server Version:**
Purpur 1.18.2

**Grim Version (Git commit or the version in the jar's name)**
Grim 2.3.4

**Relevant plugins**
ViaVersion, ViaBackwards, LuckPerms 5.4.30, Login Security 3.0.2

**Comment by MWHunter** [comment]
This is intentional for performance reasons and is required due to tracking everything with packets.

**Comment by MWHunter** [comment]
The disableGrim player variable can kind of do what you are asking.
