### ISSUE TITLE
[2.3.7] NPE when running transactions for player

### ISSUE THREAD

**Issue by noiverre** [MWHunter/Grim#574]
**Describe the bug**
```
[06:10:34 INFO]: [GrimAC] [STDOUT] An error has occurred when running transactions for player: FerRySta_
[06:10:34 WARN]: Nag author(s): '[GrimAC]' of 'GrimAC' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[06:10:34 WARN]: java.lang.NullPointerException
```

**To Reproduce**
Not sure, I was checking the server console and this happened several times, no stack traces nor anything after/before it, that's all the error prints

**Server Version:**
This server is running Paper version git-Paper-27 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: b77fe3a)

**Grim Version (Git commit or the version in the jar's name)**
2.3.7

**Relevant plugins**
ProtocolLib v5.0.0-SNAPSHOT-b569
ViaVersion 4.3.1

**Comment by MWHunter** [comment]
If you scroll up enough there should be a stack trace

**Comment by noiverre** [comment]
> If you scroll up enough there should be a stack trace

Oh yeah it was shown in the very first NPE that occurs, here it is
https://paste.gg/p/anonymous/0422db945db244c788f8371310a42391

**Comment by MWHunter** [comment]
Fixed twice in https://github.com/MWHunter/Grim/commit/992e266835ac6bc09b394733dd646575abb32b27 and https://github.com/MWHunter/Grim/commit/1b8752e7418951055a81b382b3a18fbea91d8f9f
