### ISSUE TITLE
[False] Post on Repeater false.

### ISSUE THREAD

**Issue by timof121** [MWHunter/Grim#575]
**Describe the bug**
Grim falses Post when you continously hold RMB on repeater (Tested on 1.19 client, test.grim.ac server)

**To Reproduce**
1. Go near a repeater
2. Hold RMB button on it
3. Move around while hoding it
4. It should flag post

https://streamable.com/09171l

**Server Version:**
1.19 (test.grim.ac)

**Grim Version (Git commit or the version in the jar's name)**
2.3.7

**Relevant plugins**
test.grim.ac

**Comment by DontNeedAName** [comment]
Same thing happens when clicking on signs.

**Comment by MWHunter** [comment]
Most likely fixed by https://github.com/MWHunter/Grim/commit/41f83ef1375b1f510ea21cf361ee825323c56070 although I don't know what exactly in minecraft's code is sending packets after the flying packet
