### ISSUE TITLE
Mud on older versions falses

### ISSUE THREAD

**Issue by scarfacered** [MWHunter/Grim#577]
**Describe the bug**
Walking over mud (it looks like coarse dirt on older versions) flags Simulation and Groundspoof

**Server Version:**
1.19

**Grim Version (Git commit or the version in the jar's name)**
2.3.7

**Relevant plugins**
ViaBackwards and ViaVersion

**Comment by MWHunter** [comment]
I usually don't fix these things because grim is going in front of via once packetevents supports it, but 1.18 and 1.19 is a sane enough combination that I added the via collision block in https://github.com/MWHunter/Grim/commit/0893e3e8ebd3eb1d85e2536581e0514595e3ef7a
