### ISSUE TITLE
FastBreak False triggers with Efficiency Shears

### ISSUE THREAD

**Issue by TheDeafCreeper** [MWHunter/Grim#580]
**Describe the bug**
When using shears with efficiency less that 5 and breaking wool, it tends to false flag.

**To Reproduce**
1. Enchant shears with Efficiency less than 5 (Higher falses more I believe)
2. Break wool
3. Eventually, it will start false flagging it.

**Server Version:**
git-Purpur-1623

**Grim Version (Git commit or the version in the jar's name)**
grimac-2.3.7

**Relevant plugins**
ArmorStandTools, BungeeTabListPlus, CustomHeads*, Essentials, EssentialsChat, F3NPerm, FastAsyncWorldEdit (WorldEdit), GrimAC, LiteBans, LuckPerms, PlaceholderAPI, PremiumVanish, ProtocolLib, StructureBlockLib*, UltraCustomizer, Vault, Woolsacre

**Comment by TheDeafCreeper** [comment]
Forgot to note that the false flag also occurs on the test server.

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/8060f8d547fe217e1a9f9e36bbeb0a6931c9fdb1
