### ISSUE TITLE
Elytra Falses

### ISSUE THREAD

**Issue by IceWaffles** [MWHunter/Grim#583]
**Describe the bug**
It appears that flying through rain with an elytra on a 1.18.2 server causes simulation to flag incorrectly. The user at this time was also flying over water, but I'm not sure if it affected anything.

**To Reproduce**
Fly with an elytra during rain/thunderstorm on 1.18.2 - I believe the client used was also 1.18.2, but may have been 1.19 through viaversion.

**Server Version:**
1.18.2

**Grim Version (Git commit or the version in the jar's name)**
2.3.7 (spigot release)

**Relevant plugins**
No plugins should be affecting this; I have none that affect elytra flight at all. My server is pretty much vanilla except for set homes and teleport requests, which is done through EssX.

**Comment by MWHunter** [comment]
Very likely fastmath.  Seems like if you log on while flying with fastmath, the flags are so large that fastmath mitigation sees it as a cheat rather than fastmath.

FUCK OPTIFINE

**Comment by IceWaffles** [comment]
I'm guessing you've already asked and OptiFine definitely doesn't want to remove their fastmath lol

**Comment by MWHunter** [comment]
Fixed in https://github.com/MWHunter/Grim/commit/dab8ce664d101b9837901afe1aff3c2cb16c2159

I doubt FastMath will ever be removed because sp614's ego is too large
