### ISSUE TITLE
Worldborder collisions not working

### ISSUE THREAD

**Issue by booky10** [MWHunter/Grim#584]
**Describe the bug**
Grim doesn't prevent the client from completely ignoring the worldborder and flying straight through it.
There seems to be code to prevent this, but it doesn't work.

**To Reproduce**
Client Version 1.19, recorded on `test.grim.ac`: [https://youtu.be/CSPH75bqqLY](https://youtu.be/CSPH75bqqLY)
"No Clip" just simulates the no-collision effect of spectator mode, without being in spectator mode.

**Server Version:**
`test.grim.ac`

**Grim Version (Git commit or the version in the jar's name)**
`test.grim.ac`

**Relevant plugins**
`test.grim.ac`

**Comment by MWHunter** [comment]
https://github.com/sp614x/optifine/issues/5578 really needs to be fixed

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/4d5335b1a399c0793d814ac0323d309aa26ecf77

**Comment by MWHunter** [comment]
meant to link https://github.com/MWHunter/Grim/commit/3a42d74776eb5823ba76745b891a6ed79978a433
