### ISSUE TITLE
false Simulation upon world changes

### ISSUE THREAD

**Issue by noobi04** [MWHunter/Grim#585]
**Describe the bug**
As soon as the player switches between worlds set up with multiverse false simulation flags appear. Since the simulation flag defaultly contains about 4 checks we were unsure if the issue is connected to the simulation check itself. After we removed the 3 checks and simulation being the only one left the issue still exists. 

**To Reproduce**
Since it might be easier to follow up using a video here is the link:
https://youtu.be/ie9TxhqqtCI

**Server Version:**
Spigot 1.8.8

**Grim Version (Git commit or the version in the jar's name)**
grimac-2.3.7-all.jar

**Relevant plugins**
![Screenshot_32](https://user-images.githubusercontent.com/107631362/175399124-23005360-7188-4d6c-becf-0c553fa9c5a2.png)

Attempts i have tried to fix:
I ran the plugin without any other plugin except multiverse, protocollib, grim. Issue still persists.

**Comment by Abel156** [comment]
how 2 use karhu with grimac in server?
so cool

**Comment by noobi04** [comment]
Simple put both in plugins folder and start.
As said above this still happens regardless if other plugins are used.

**Comment by MWHunter** [comment]
Possibly fixed by https://github.com/MWHunter/Grim/commit/5e828357b79cc03515f0267e2d2779b2aaad9e5d

Re-open if this is still an issue
