### ISSUE TITLE
Running and breaking blocks at the same time

### ISSUE THREAD

**Issue by Ayazerzurum2** [MWHunter/Grim#586]
**Describe the bug**
Running and breaking blocks at the same time Flags simulation and groundspoof

**To Reproduce**
https://www.youtube.com/watch?v=LT1VL6OfGpM
1.18.2 client

**Server Version:** 1.18.2

**Grim Version (Git commit or the version in the jar's name)**
test server on 24.06.22
**Relevant plugins**
test server on 24.06.22

**Comment by MWHunter** [comment]
likely fixed by https://github.com/MWHunter/Grim/issues/580
