### ISSUE TITLE
righ click on fence triggers misc check

### ISSUE THREAD

**Issue by Hyronymos1337** [MWHunter/Grim#587]
**Describe the bug**
https://www.youtube.com/watch?v=t9R6jEi21Ko)

**To Reproduce**
https://www.youtube.com/watch?v=t9R6jEi21Ko

**Server Version:**
1.19

**Grim Version (Git commit or the version in the jar's name)**
latest release

**Relevant plugins**
viaversion, viabackwards, viarewind

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/0c50770a4caeb09d18265c958a59125e8875e648
