### ISSUE TITLE
Scaffolding issues above Y: 256

### ISSUE THREAD

**Issue by ArtelGG** [MWHunter/Grim#588]
**Describe the bug**
When walking through scaffolding (other blocks *may* be affected, however, I didn't find any after some quick tests) above Y: 256, you will constantly fall through the scaffolding as if you are sneaking and your movement will be jittery (due to the movement being cancelled)

**To Reproduce**
https://www.youtube.com/watch?v=UiEEOIx4ZXg

**Server Version:**
Tested and reproduced on Paper-386 (1.18.2) and Paper-36 (1.19).

**Grim Version (Git commit or the version in the jar's name)**
2.3.7

**Relevant plugins**
N/A

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/ab4358052d51194b192a0a24ee33a209d7d0f34e
