### ISSUE TITLE
grim false simulation on jumpreset

### ISSUE THREAD

**Issue by noobi04** [MWHunter/Grim#591]
**Describe the bug**
When jumping into a hit while your opponent is walking towards you the player gets flagged for simulation and is forced back to the ground.

**To Reproduce**
https://www.youtube.com/watch?v=2-MuPiiLaIQ

**Server Version:**
Spigot 1.8.8

**Grim Version (Git commit or the version in the jar's name)**
grimac-2.3.9-all.jar

**Relevant plugins**
none, since the issue also happens on server without any plugins (tested)

**Comment by MWHunter** [comment]
Unable to reproduce

**Comment by MWHunter** [comment]
![kb](https://user-images.githubusercontent.com/49797025/175799128-65ba3159-e63f-4c94-a276-aa0a6c76b343.png)

**Comment by noobi04** [comment]
i could try to reproduce on test server if there is one.

**Comment by noobi04** [comment]
on test server its also possible. 
somehow without any simulation flag. 
but still the player is being forced back to the ground.

i have even tested it on different server of different players with different players. 
issue happened on every single server.

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/a531af46f8c952a64b258d8b482dad26df4409f3

**Comment by noobi04** [comment]
ty
