### ISSUE TITLE
GrimAPI FlagEvent

### ISSUE THREAD

**Issue by Abel156** [MWHunter/Grim#594]
**Describe the bug**
When I use the flagevent of the developer API
If the player has a flag before setCancelled(true), this value will always be displayed, but will not increase
I think it should become not incrementing and at the same time not showing

**To Reproduce**
FlagEvent and event.setCancelled(true)
If the player owns the flag before this canceled operation
Then after canceled, this flag will always be displayed, but it will not increase
it should change to not show and not increment

**Server Version:**
1.8 foxspigot

**Grim Version (Git commit or the version in the jar's name)**
grimac-2.3.9-all

**Relevant plugins**
none

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/4ec7e9a006714933d730c0f42d6140b70f80aa2d
