### ISSUE TITLE
Unable to get player of flagevent

### ISSUE THREAD

**Issue by Abel156** [MWHunter/Grim#599]
**Describe the bug**
    @EventHandler
    public void event(FlagEvent event){
        System.out.println(event.getPlayer().getName());
    }
will output null

**To Reproduce**
    @EventHandler
    public void event(FlagEvent event){
        System.out.println(event.getPlayer().getName());
    }
will output null

**Server Version:**
1.8

**Grim Version (Git commit or the version in the jar's name)**
e500b0ad5763347e3155aade65bc3d3b58045156

**Relevant plugins**
none

**Comment by AoElite** [comment]
Fixed https://github.com/MWHunter/GrimAPI/commit/ad52ad56a932dde32c1c2468baaef73df08c8355
