### ISSUE TITLE
GroundSpoof/Simulation Elytra falses.

### ISSUE THREAD

**Issue by jtJava** [MWHunter/Grim#600]
**Describe the bug**
GroundSpoof/Simulation falses, also GroundSpoof false everytime I join test server.

**To Reproduce**
[Video is preferred.   If video is not possible, for bypasses, the hacked client name, version, module, module settings, and the check being bypassed is enough.  For false positives, steps to reproduce is fine also.](https://youtu.be/vkUZstUmr2g)
1.19 client

**Server Version:**
Test Server

**Grim Version (Git commit or the version in the jar's name)**

**Relevant plugins**
Or all plugins if you are unsure

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/162170a7b0d817018202fd62a6d7a9b4bd549918
