### ISSUE TITLE
netty error spam

### ISSUE THREAD

**Issue by DeeKaPPy** [MWHunter/Grim#601]
**Describe the bug**
When a player joined th server grim started spaming with a netty error https://www.toptal.com/developers/hastebin/ejatuneqik.yaml

**To Reproduce**
Player join the server

**Server Version:**
1.8 (git-TacoSpigot-7bb7d3f3 (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT))

**Grim Version (Git commit or the version in the jar's name)**
2.3.9-all

**Relevant plugins**

**Comment by MWHunter** [comment]
the paste disappeared

**Comment by MWHunter** [comment]
Closing because the paste is gone
